# load full_merged dataset

In [3]:
data = pd.read_csv('../../private_WY/largeDataset/full_merged_dataset_v1.csv', parse_dates=['date'])
print(data.shape)
data.head()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (7,8,9,10,11,12,13,14,15,16,18,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(4617600, 29)

,date,year,month,day,dayofweek,weekday,weekend,tmax,tmin,tavg,...,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed,station_nbr,store_nbr,item_nbr,units
0,2012-01-01,2012,1,1,6,False,True,52,31,42,...,0.05,29.78,29.92,3.6,20,4.6,1,1,1,0
1,2012-01-01,2012,1,1,6,False,True,52,31,42,...,0.05,29.78,29.92,3.6,20,4.6,1,1,2,0
2,2012-01-01,2012,1,1,6,False,True,52,31,42,...,0.05,29.78,29.92,3.6,20,4.6,1,1,3,0
3,2012-01-01,2012,1,1,6,False,True,52,31,42,...,0.05,29.78,29.92,3.6,20,4.6,1,1,4,0
4,2012-01-01,2012,1,1,6,False,True,52,31,42,...,0.05,29.78,29.92,3.6,20,4.6,1,1,5,0

### rename codesum 
- blank -> plain weather
- codesum -> abnormal weather (in `Cdsm_Ch` column)

In [73]:
def ch_codesum(codesum):
    if codesum == ' ':
        return "Plain"
    else:
        return codesum

In [8]:
data['codesum'] = data['codesum'].apply(ch_codesum)

In [10]:
def compare_codesum(codesum):
    if codesum =="Plain":
        return codesum
    else:
        return "Abnormal"

In [11]:
data["Cdsm_Ch"] = data['codesum'].apply(compare_codesum)

# load 'holiday' data

In [36]:
holiday = pd.read_csv('../data/04. holiday_data')

In [37]:
holiday = holiday.drop('Unnamed: 0', axis=1)

In [38]:
holiday.tail()

    year       day         date       holiday
26  2014    Monday  September01      LaborDay
27  2014    Monday    October13   ColumbusDay
28  2014   Tuesday   November11   VeteransDay
29  2014  Thursday   November27  Thanksgiving
30  2014  Thursday   December25  ChristmasDay

### Rearrange 'date'

In [39]:
def convert_day(day):
    if day == 'Monday':
        return 'Mon'
    elif day == 'Tuesday':
        return 'Tue'
    elif day == 'Wednesday':
        return 'Wed'
    elif day == 'Thursday':
        return 'Thu'
    elif day == 'Friday':
        return 'Fri'
    elif day == 'Saturday':
        return 'Sat'
    elif day == 'Sunday':
        return 'Sat'

In [40]:
holiday['dayofweek'] = holiday['day'].apply(convert_day)

In [41]:
holiday = holiday.drop('day', axis=1)

In [42]:
holiday.tail()

    year         date       holiday dayofweek
26  2014  September01      LaborDay       Mon
27  2014    October13   ColumbusDay       Mon
28  2014   November11   VeteransDay       Tue
29  2014   November27  Thanksgiving       Thu
30  2014   December25  ChristmasDay       Thu

In [43]:
def apply_day(date):
    return date[-2:]

In [44]:
holiday['day'] = holiday['date'].apply(apply_day)

In [45]:
holiday

    year         date                 holiday dayofweek day
0   2012    January02     NewYearsDay(inlieu)       Mon  02
1   2012    January16  MartinLutherKingJr.Day       Mon  16
2   2012   February20          Presidents'Day       Mon  20
3   2012        May28             MemorialDay       Mon  28
4   2012       July04         IndependenceDay       Wed  04
5   2012  September03                LaborDay       Mon  03
6   2012    October08             ColumbusDay       Mon  08
7   2012   November12             VeteransDay       Mon  12
8   2012   November22            Thanksgiving       Thu  22
9   2012   November23    DayafterThanksgiving       Fri  23
10  2012   December25            ChristmasDay       Tue  25
11  2013    January01             NewYearsDay       Tue  01
12  2013    January21  MartinLutherKingJr.Day       Mon  21
13  2013   February18          Presidents'Day       Mon  18
14  2013        May27             MemorialDay       Mon  27
15  2013       July04         IndependenceDay       Thu  04
16  2013  September02                LaborDay       Mon  02
17  2013    October14             ColumbusDay       Mon  14
18  2013   November11             VeteransDay       Mon  11
19  2013   November28            Thanksgiving       Thu  28
20  2013   December25            ChristmasDay       Wed  25
21  2014    January01             NewYearsDay       Wed  01
22  2014    January20  MartinLutherKingJr.Day       Mon  20
23  2014   February17          Presidents'Day       Mon  17
24  2014        May26             MemorialDay       Mon  26
25  2014       July04         IndependenceDay       Fri  04
26  2014  September01                LaborDay       Mon  01
27  2014    October13             ColumbusDay       Mon  13
28  2014   November11             VeteransDay       Tue  11
29  2014   November27            Thanksgiving       Thu  27
30  2014   December25            ChristmasDay       Thu  25

In [46]:
def apply_month(date):
    return date[:-2]

In [47]:
holiday['month'] = holiday['date'].apply(apply_month)

In [49]:
def convert_month(month):
    if month == 'January':
        return '01'
    elif month == 'February':
        return '02'
    elif month == 'March':
        return '03'
    elif month == 'April':
        return '04'
    elif month == 'May':
        return '05'
    elif month == 'June':
        return '06'
    elif month == 'July':
        return '07'
    elif month == 'August':
        return '08'
    elif month == 'September':
        return '09'
    elif month == 'October':
        return '10'
    elif month == 'November':
        return '11'
    elif month == 'December':
        return '12'

In [50]:
holiday['month'] = holiday['month'].apply(convert_month)

In [53]:
holiday = holiday.drop('date', axis = 1)

In [79]:
holiday['date'] = holiday['year'].astype(str) + '-' + holiday['month'].astype(str) + '-' + holiday['day'].astype(str)

In [80]:
holiday2 = pd.DataFrame(columns=['date', 'year', 'month', 'day', 'dayofweek', 'holiday'])

In [81]:
holiday2['date'] = holiday['date']
holiday2['year'] = holiday['year']
holiday2['month'] = holiday['month']
holiday2['day'] = holiday['day']
holiday2['dayofweek'] = holiday['dayofweek']
holiday2['holiday'] = holiday['holiday']

In [82]:
holiday = holiday2

In [83]:
holiday

          date  year month day dayofweek                 holiday
0   2012-01-02  2012    01  02       Mon     NewYearsDay(inlieu)
1   2012-01-16  2012    01  16       Mon  MartinLutherKingJr.Day
2   2012-02-20  2012    02  20       Mon          Presidents'Day
3   2012-05-28  2012    05  28       Mon             MemorialDay
4   2012-07-04  2012    07  04       Wed         IndependenceDay
5   2012-09-03  2012    09  03       Mon                LaborDay
6   2012-10-08  2012    10  08       Mon             ColumbusDay
7   2012-11-12  2012    11  12       Mon             VeteransDay
8   2012-11-22  2012    11  22       Thu            Thanksgiving
9   2012-11-23  2012    11  23       Fri    DayafterThanksgiving
10  2012-12-25  2012    12  25       Tue            ChristmasDay
11  2013-01-01  2013    01  01       Tue             NewYearsDay
12  2013-01-21  2013    01  21       Mon  MartinLutherKingJr.Day
13  2013-02-18  2013    02  18       Mon          Presidents'Day
14  2013-05-27  2013    05  27       Mon             MemorialDay
15  2013-07-04  2013    07  04       Thu         IndependenceDay
16  2013-09-02  2013    09  02       Mon                LaborDay
17  2013-10-14  2013    10  14       Mon             ColumbusDay
18  2013-11-11  2013    11  11       Mon             VeteransDay
19  2013-11-28  2013    11  28       Thu            Thanksgiving
20  2013-12-25  2013    12  25       Wed            ChristmasDay
21  2014-01-01  2014    01  01       Wed             NewYearsDay
22  2014-01-20  2014    01  20       Mon  MartinLutherKingJr.Day
23  2014-02-17  2014    02  17       Mon          Presidents'Day
24  2014-05-26  2014    05  26       Mon             MemorialDay
25  2014-07-04  2014    07  04       Fri         IndependenceDay
26  2014-09-01  2014    09  01       Mon                LaborDay
27  2014-10-13  2014    10  13       Mon             ColumbusDay
28  2014-11-11  2014    11  11       Tue             VeteransDay
29  2014-11-27  2014    11  27       Thu            Thanksgiving
30  2014-12-25  2014    12  25       Thu            ChristmasDay

#### save holiday as csv

In [84]:
holiday.to_csv('holiday')

In [85]:
test = pd.read_csv('holiday', index_col = 0)
test

          date  year  month  day dayofweek                 holiday
0   2012-01-02  2012      1    2       Mon     NewYearsDay(inlieu)
1   2012-01-16  2012      1   16       Mon  MartinLutherKingJr.Day
2   2012-02-20  2012      2   20       Mon          Presidents'Day
3   2012-05-28  2012      5   28       Mon             MemorialDay
4   2012-07-04  2012      7    4       Wed         IndependenceDay
5   2012-09-03  2012      9    3       Mon                LaborDay
6   2012-10-08  2012     10    8       Mon             ColumbusDay
7   2012-11-12  2012     11   12       Mon             VeteransDay
8   2012-11-22  2012     11   22       Thu            Thanksgiving
9   2012-11-23  2012     11   23       Fri    DayafterThanksgiving
10  2012-12-25  2012     12   25       Tue            ChristmasDay
11  2013-01-01  2013      1    1       Tue             NewYearsDay
12  2013-01-21  2013      1   21       Mon  MartinLutherKingJr.Day
13  2013-02-18  2013      2   18       Mon          Presidents'Day
14  2013-05-27  2013      5   27       Mon             MemorialDay
15  2013-07-04  2013      7    4       Thu         IndependenceDay
16  2013-09-02  2013      9    2       Mon                LaborDay
17  2013-10-14  2013     10   14       Mon             ColumbusDay
18  2013-11-11  2013     11   11       Mon             VeteransDay
19  2013-11-28  2013     11   28       Thu            Thanksgiving
20  2013-12-25  2013     12   25       Wed            ChristmasDay
21  2014-01-01  2014      1    1       Wed             NewYearsDay
22  2014-01-20  2014      1   20       Mon  MartinLutherKingJr.Day
23  2014-02-17  2014      2   17       Mon          Presidents'Day
24  2014-05-26  2014      5   26       Mon             MemorialDay
25  2014-07-04  2014      7    4       Fri         IndependenceDay
26  2014-09-01  2014      9    1       Mon                LaborDay
27  2014-10-13  2014     10   13       Mon             ColumbusDay
28  2014-11-11  2014     11   11       Tue             VeteransDay
29  2014-11-27  2014     11   27       Thu            Thanksgiving
30  2014-12-25  2014     12   25       Thu            ChristmasDay

In [ ]:
def is_holiday(date):
    if date in holiday:
        return 'holiday'
    else:
        return 'workday'