In [1]:
from jw_package import *

import configuration completed !
train + key + weather merging started
train + key + weather merging finished
function configuration completed !
Good to go !

In [8]:
tmp = pd.read_csv('tmp.csv',index_col=0)
X = pd.read_csv('X.csv',index_col=0)
y = pd.read_csv('y.csv',index_col=0)

In [9]:
tmp

,date,store_nbr,item_nbr,units,cool,depart,heat,preciptotal,resultdir,snowfall,is_holiday,codesum
0,2012-01-01,1,9,29,0.000000,8.0,23.000000,0.050000,20.0,0.0,1,1
1,2012-01-01,1,28,2,0.000000,8.0,23.000000,0.050000,20.0,0.0,1,1
2,2012-01-01,1,51,1,0.000000,8.0,23.000000,0.050000,20.0,0.0,1,1
3,2012-01-02,1,9,60,0.000000,11.0,24.000000,0.010000,24.0,0.0,1,0
4,2012-01-02,1,28,5,0.000000,11.0,24.000000,0.010000,24.0,0.0,1,0
5,2012-01-02,1,51,1,0.000000,11.0,24.000000,0.010000,24.0,0.0,1,0
6,2012-01-03,1,9,15,0.000000,6.0,43.000000,0.000000,31.0,0.0,0,0
7,2012-01-03,1,28,9,0.000000,6.0,43.000000,0.000000,31.0,0.0,0,0
8,2012-01-04,1,9,20,0.000000,2.0,46.000000,0.000000,27.0,0.8,0,0
9,2012-01-04,1,28,3,0.000000,2.0,46.000000,0.000000,27.0,0.8,0,0
10,2012-01-05,1,9,16,0.000000,1.0,33.000000,0.000000,25.0,0.1,0,0
11,2012-01-05,1,28,1,0.000000,1.0,33.000000,0.000000,25.0,0.1,0,0
12,2012-01-06,1,9,12,0.000000,4.0,29.000000,0.118415,1.0,0.0,0,1
13,2012-01-06,1,28,2,0.000000,4.0,29.000000,0.118415,1.0,0.0,0,1
14,2012-01-07,1,9,2,0.000000,5.0,22.000000,0.000000,26.0,0.0,1,0
15,2012-01-07,1,28,1,0.000000,5.0,22.000000,0.000000,26.0,0.0,1,0
16,2012-01-08,1,9,22,0.000000,1.0,29.000000,0.000000,30.0,0.1,1,0
17,2012-01-08,1,28,4,0.000000,1.0,29.000000,0.000000,30.0,0.1,1,0
18,2012-01-08,1,51,1,0.000000,1.0,29.000000,0.000000,30.0,0.1,1,0
19,2012-01-09,1,9,50,0.000000,4.0,34.000000,0.000000,23.0,0.0,0,0
20,2012-01-09,1,28,1,0.000000,4.0,34.000000,0.000000,23.0,0.0,0,0
21,2012-01-09,1,51,1,0.000000,4.0,34.000000,0.000000,23.0,0.0,0,0
22,2012-01-10,1,9,25,0.000000,1.0,27.000000,0.118415,25.0,0.1,0,0
23,2012-01-11,1,9,26,0.000000,17.0,33.000000,0.000000,7.0,0.0,0,0
24,2012-01-11,1,28,1,0.000000,17.0,33.000000,0.000000,7.0,0.0,0,0
25,2012-01-11,1,40,4,0.000000,17.0,33.000000,0.000000,7.0,0.0,0,0
26,2012-01-11,1,51,3,0.000000,17.0,33.000000,0.000000,7.0,0.0,0,0
27,2012-01-12,1,9,32,0.000000,17.0,29.000000,0.690000,5.0,0.0,0,1
28,2012-01-12,1,28,2,0.000000,17.0,29.000000,0.690000,5.0,0.0,0,1
29,2012-01-12,1,51,4,0.000000,17.0,29.000000,0.690000,5.0,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
118666,2014-10-19,35,16,25,1.866667,4.8,4.466667,0.130333,31.0,0.0,1,0
118667,2014-10-19,35,66,11,1.866667,4.8,4.466667,0.130333,31.0,0.0,1,0
118668,2014-10-20,35,16,19,1.866667,4.8,4.466667,0.130333,24.0,0.0,0,0
118669,2014-10-20,35,66,14,1.866667,4.8,4.466667,0.130333,24.0,0.0,0,0
118670,2014-10-21,35,16,10,1.866667,4.8,4.466667,0.130333,9.0,0.0,0,0
118671,2014-10-21,35,50,1,1.866667,4.8,4.466667,0.130333,9.0,0.0,0,0
118672,2014-10-21,35,66,11,1.866667,4.8,4.466667,0.130333,9.0,0.0,0,0
118673,2014-10-22,35,16,11,1.866667,4.8,4.466667,0.130333,3.0,0.0,0,0
118674,2014-10-22,35,66,10,1.866667,4.8,4.466667,0.130333,3.0,0.0,0,0
118675,2014-10-23,35,16,10,1.866667,4.8,4.466667,0.130333,1.0,0.0,0,0
118676,2014-10-23,35,66,9,1.866667,4.8,4.466667,0.130333,1.0,0.0,0,0
118677,2014-10-24,35,16,18,1.866667,4.8,4.466667,0.130333,32.0,0.0,0,0
118678,2014-10-24,35,66,9,1.866667,4.8,4.466667,0.130333,32.0,0.0,0,0
118679,2014-10-25,35,16,25,1.866667,4.8,4.466667,0.130333,26.0,0.0,1,0
118680,2014-10-25,35,50,3,1.866667,4.8,4.466667,0.130333,26.0,0.0,1,0
118681,2014-10-25,35,66,5,1.866667,4.8,4.466667,0.130333,26.0,0.0,1,0
118682,2014-10-26,35,16,23,1.866667,4.8,4.466667,0.130333,28.0,0.0,1,0
118683,2014-10-26,35,66,13,1.866667,4.8,4.466667,0.130333,28.0,0.0,1,0
118684,2014-10-27,35,16,17,1.866667,4.8,4.466667,0.130333,28.0,0.0,0,0
118685,2014-10-27,35,50,2,1.866667,4.8,4.466667,0.130333,28.0,0.0,0,0
118686,2014-10-27,35,66,11,1.866667,4.8,4.466667,0.130333,28.0,0.0,0,0
118687,2014-10-28,35,16,11,1.866667,4.8,4.466667,0.130333,19.0,0.0,0,0
118688,2014-10-28,35,50,3,1.866667,4.8,4.466667,0.130333,19.0,0.0,0,0
118689,2014-10-28,35,66,11,1.866667,4.8,4.466667,0.130333,19.0,0.0,0,0
118690,2014-10-29,35,16,20,1.866667,4.8,4.466667,0.130333,23.0,0.0,0,0
118691,2014-10-29,35,66,14,1.866667,4.8,4.466667,0.130333,23.0,0.0,0,0
118692,2014-10-30,35,16,16,1.866667,4.8,4.466667,0.130333,30.0,0.0,0,0
118693,2014-10-30,35,66,6,1.866667,4.8,4.466667,0.130333,30.0,0.0,0,0
118694,2014-10-31,35,16,18,1.866667,4.8,4.466667,0.130333,5.0,0.0,0,0
118695,2014-10-31,35,66,10,1.866667,4.8,4.466667,0.130333,5.0,0.0,0,0

In [10]:
X

,store_nbr,item_nbr,cool,heat,preciptotal,snowfall,is_holiday
0,1,9,0.000000,23.000000,0.050000,0.0,1
1,1,28,0.000000,23.000000,0.050000,0.0,1
2,1,51,0.000000,23.000000,0.050000,0.0,1
3,1,9,0.000000,24.000000,0.010000,0.0,1
4,1,28,0.000000,24.000000,0.010000,0.0,1
5,1,51,0.000000,24.000000,0.010000,0.0,1
6,1,9,0.000000,43.000000,0.000000,0.0,0
7,1,28,0.000000,43.000000,0.000000,0.0,0
8,1,9,0.000000,46.000000,0.000000,0.8,0
9,1,28,0.000000,46.000000,0.000000,0.8,0
10,1,9,0.000000,33.000000,0.000000,0.1,0
11,1,28,0.000000,33.000000,0.000000,0.1,0
12,1,9,0.000000,29.000000,0.118415,0.0,0
13,1,28,0.000000,29.000000,0.118415,0.0,0
14,1,9,0.000000,22.000000,0.000000,0.0,1
15,1,28,0.000000,22.000000,0.000000,0.0,1
16,1,9,0.000000,29.000000,0.000000,0.1,1
17,1,28,0.000000,29.000000,0.000000,0.1,1
18,1,51,0.000000,29.000000,0.000000,0.1,1
19,1,9,0.000000,34.000000,0.000000,0.0,0
20,1,28,0.000000,34.000000,0.000000,0.0,0
21,1,51,0.000000,34.000000,0.000000,0.0,0
22,1,9,0.000000,27.000000,0.118415,0.1,0
23,1,9,0.000000,33.000000,0.000000,0.0,0
24,1,28,0.000000,33.000000,0.000000,0.0,0
25,1,40,0.000000,33.000000,0.000000,0.0,0
26,1,51,0.000000,33.000000,0.000000,0.0,0
27,1,9,0.000000,29.000000,0.690000,0.0,0
28,1,28,0.000000,29.000000,0.690000,0.0,0
29,1,51,0.000000,29.000000,0.690000,0.0,0
...,...,...,...,...,...,...,...
118666,35,16,1.866667,4.466667,0.130333,0.0,1
118667,35,66,1.866667,4.466667,0.130333,0.0,1
118668,35,16,1.866667,4.466667,0.130333,0.0,0
118669,35,66,1.866667,4.466667,0.130333,0.0,0
118670,35,16,1.866667,4.466667,0.130333,0.0,0
118671,35,50,1.866667,4.466667,0.130333,0.0,0
118672,35,66,1.866667,4.466667,0.130333,0.0,0
118673,35,16,1.866667,4.466667,0.130333,0.0,0
118674,35,66,1.866667,4.466667,0.130333,0.0,0
118675,35,16,1.866667,4.466667,0.130333,0.0,0
118676,35,66,1.866667,4.466667,0.130333,0.0,0
118677,35,16,1.866667,4.466667,0.130333,0.0,0
118678,35,66,1.866667,4.466667,0.130333,0.0,0
118679,35,16,1.866667,4.466667,0.130333,0.0,1
118680,35,50,1.866667,4.466667,0.130333,0.0,1
118681,35,66,1.866667,4.466667,0.130333,0.0,1
118682,35,16,1.866667,4.466667,0.130333,0.0,1
118683,35,66,1.866667,4.466667,0.130333,0.0,1
118684,35,16,1.866667,4.466667,0.130333,0.0,0
118685,35,50,1.866667,4.466667,0.130333,0.0,0
118686,35,66,1.866667,4.466667,0.130333,0.0,0
118687,35,16,1.866667,4.466667,0.130333,0.0,0
118688,35,50,1.866667,4.466667,0.130333,0.0,0
118689,35,66,1.866667,4.466667,0.130333,0.0,0
118690,35,16,1.866667,4.466667,0.130333,0.0,0
118691,35,66,1.866667,4.466667,0.130333,0.0,0
118692,35,16,1.866667,4.466667,0.130333,0.0,0
118693,35,66,1.866667,4.466667,0.130333,0.0,0
118694,35,16,1.866667,4.466667,0.130333,0.0,0
118695,35,66,1.866667,4.466667,0.130333,0.0,0

In [11]:
y

        units
0          29
1           2
2           1
3          60
4           5
5           1
6          15
7           9
8          20
9           3
10         16
11          1
12         12
13          2
14          2
15          1
16         22
17          4
18          1
19         50
20          1
21          1
22         25
23         26
24          1
25          4
26          3
27         32
28          2
29          4
...       ...
118666     25
118667     11
118668     19
118669     14
118670     10
118671      1
118672     11
118673     11
118674     10
118675     10
118676      9
118677     18
118678      9
118679     25
118680      3
118681      5
118682     23
118683     13
118684     17
118685      2
118686     11
118687     11
118688      3
118689     11
118690     20
118691     14
118692     16
118693      6
118694     18
118695     10

[118696 rows x 1 columns]

In [12]:
formula = 'units ~ C(store_nbr) + C(item_nbr)+ scale(cool) + scale(heat) + scale(preciptotal) + scale(snowfall) + is_holiday'

In [13]:
model = sm.OLS.from_formula(formula, data=pd.concat([X, y], axis=1))
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  units   R-squared:                       0.593
Model:                            OLS   Adj. R-squared:                  0.593
Method:                 Least Squares   F-statistic:                     1088.
Date:                Mon, 12 Mar 2018   Prob (F-statistic):               0.00
Time:                        22:04:02   Log-Likelihood:            -5.7588e+05
No. Observations:              118696   AIC:                         1.152e+06
Df Residuals:                  118536   BIC:                         1.154e+06
Df Model:                         159
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             15.0595      2.135      7.055      0.000      10.876      19.243
C(store_nbr)[T.2]     32.6025      1.204     27.071      0.000      30.242      34.963
C(store_nbr)[T.3]     22.6023      1.155     19.564      0.000      20.338      24.867
C(store_nbr)[T.4]     77.9195      1.300     59.940      0.000      75.372      80.467
C(store_nbr)[T.5]     26.6508      1.234     21.593      0.000      24.232      29.070
C(store_nbr)[T.6]     17.3447      1.170     14.819      0.000      15.051      19.639
C(store_nbr)[T.7]     29.8772      1.277     23.396      0.000      27.374      32.380
C(store_nbr)[T.8]      9.3331      1.262      7.393      0.000       6.859      11.807
C(store_nbr)[T.9]     18.0202      1.170     15.399      0.000      15.727      20.314
C(store_nbr)[T.10]    30.5944      1.167     26.214      0.000      28.307      32.882
C(store_nbr)[T.11]    10.7005      1.162      9.211      0.000       8.424      12.977
C(store_nbr)[T.12]    33.1949      1.222     27.170      0.000      30.800      35.590
C(store_nbr)[T.13]    37.1392      1.246     29.807      0.000      34.697      39.581
C(store_nbr)[T.14]   -31.9646      1.211    -26.389      0.000     -34.339     -29.591
C(store_nbr)[T.15]    31.7078      1.119     28.333      0.000      29.514      33.901
C(store_nbr)[T.16]    53.3828      1.278     41.756      0.000      50.877      55.889
C(store_nbr)[T.17]    92.5503      1.184     78.179      0.000      90.230      94.871
C(store_nbr)[T.18]     5.1037      1.222      4.176      0.000       2.708       7.499
C(store_nbr)[T.19]    19.2151      1.362     14.110      0.000      16.546      21.884
C(store_nbr)[T.20]    37.0594      1.280     28.949      0.000      34.550      39.569
C(store_nbr)[T.21]    -2.6268      1.206     -2.178      0.029      -4.991      -0.262
C(store_nbr)[T.22]    14.5922      1.153     12.651      0.000      12.331      16.853
C(store_nbr)[T.23]    -6.0598      1.185     -5.115      0.000      -8.382      -3.738
C(store_nbr)[T.24]    85.0190      4.489     18.937      0.000      76.220      93.818
C(store_nbr)[T.25]    41.7400      1.108     37.656      0.000      39.567      43.913
C(store_nbr)[T.26]     6.8666      1.177      5.836      0.000       4.560       9.173
C(store_nbr)[T.27]     9.0300      1.137      7.943      0.000       6.802      11.258
C(store_nbr)[T.28]     3.5248      1.192      2.958      0.003       1.189       5.861
C(store_nbr)[T.29]    18.3360      1.276     14.366      0.000      15.834      20.838
C(store_nbr)[T.30]    47.1769      1.230     38.340      0.000      44.765      49.589
C(store_nbr)[T.31]    25.7526      1.117     23.065      0.000      23.564      27.941
C(store_nbr)[T.32]     4.3047      1.087      3.960      0.000       2.174       6.435
C(store_nbr)[T.33]    87.5668      1.169     74.921      0.000      85.276      89.858
C(store_nbr)[T.34]    31.1074      1.115     27.906      0.000      28.923      33.292
C(store_nbr)[T.35]    24.7102      1.385     17.841      0.000      21.996      27.425
C(store_nbr)[T.36]   -15.5810      1.181    -13.197      0.000     -17.895     -13.267
C(store_nbr)[T.37]     8.8933      1.155      7.701      0.000       6.630      11.157
C(store_nbr)[T.38]    37.9899      1.113     34.120      0.000      35.808      40.172
C(store_nbr)[T.39]   -31.6927      1.288    -24.599      0.000     -34.218     -29.167
C(store_nbr)[T.40]    13.7781      1.129     12.205      0.000      11.565      15.991
C(store_nbr)[T.41]    24.5899      1.180     20.834      0.000      22.277      26.903
C(store_nbr)[T.42]    11.5322      1.215      9.489      0.000       9.150      13.914
C(store_nbr)[T.43]    35.9809      1.247     28.861      0.000      33.537      38.424
C(store_nbr)[T.44]    16.0720      1.191     13.499      0.000      13.738      18.405
C(store_nbr)[T.45]   -17.4649      1.333    -13.100      0.000     -20.078     -14.852
C(item_nbr)[T.2]     -24.8266      2.264    -10.964      0.000     -29.265     -20.388
C(item_nbr)[T.3]     -51.1283      2.866    -17.842      0.000     -56.745     -45.512
C(item_nbr)[T.4]       0.6952      3.156      0.220      0.826      -5.490       6.880
C(item_nbr)[T.5]      15.7750      1.980      7.968      0.000      11.895      19.655
C(item_nbr)[T.6]     -61.2539      4.915    -12.463      0.000     -70.887     -51.621
C(item_nbr)[T.7]     -46.3499      2.720    -17.042      0.000     -51.680     -41.019
C(item_nbr)[T.8]      -3.0772      2.377     -1.295      0.195      -7.736       1.581
C(item_nbr)[T.9]      18.9257      1.946      9.726      0.000      15.112      22.740
C(item_nbr)[T.10]    -34.1781      2.679    -12.760      0.000     -39.428     -28.928
C(item_nbr)[T.11]    -49.5289      2.711    -18.268      0.000     -54.843     -44.215
C(item_nbr)[T.12]    -59.3332      2.672    -22.205      0.000     -64.570     -54.096
C(item_nbr)[T.13]    -62.1589      2.902    -21.422      0.000     -67.846     -56.472
C(item_nbr)[T.14]    -32.8035      3.211    -10.215      0.000     -39.097     -26.510
C(item_nbr)[T.15]    -26.5550      2.334    -11.378      0.000     -31.129     -21.981
C(item_nbr)[T.16]    -18.6476      2.030     -9.188      0.000     -22.625     -14.670
C(item_nbr)[T.17]    -49.1239      2.596    -18.926      0.000     -54.211     -44.037
C(item_nbr)[T.18]    -54.7688      2.699    -20.291      0.000     -60.059     -49.478
C(item_nbr)[T.19]    -22.0055      2.599     -8.465      0.000     -27.100     -16.910
C(item_nbr)[T.20]    -42.3027      2.536    -16.682      0.000     -47.273     -37.332
C(item_nbr)[T.21]    -34.7242      2.266    -15.324      0.000     -39.166     -30.283
C(item_nbr)[T.22]      2.7042      4.025      0.672      0.502      -5.186      10.594
C(item_nbr)[T.23]    -18.8394      2.200     -8.564      0.000     -23.151     -14.528
C(item_nbr)[T.24]    -32.5336      2.888    -11.266      0.000     -38.194     -26.874
C(item_nbr)[T.25]     56.0766      2.191     25.598      0.000      51.783      60.370
C(item_nbr)[T.26]      3.0263      2.434      1.243      0.214      -1.744       7.796
C(item_nbr)[T.27]    -85.7547      2.386    -35.937      0.000     -90.432     -81.078
C(item_nbr)[T.28]    -13.1928      2.370     -5.567      0.000     -17.838      -8.548
C(item_nbr)[T.29]    -10.7616      2.525     -4.262      0.000     -15.711      -5.812
C(item_nbr)[T.30]     -1.0592      2.179     -0.486      0.627      -5.330       3.211
C(item_nbr)[T.31]    -48.5128      2.683    -18.082      0.000     -53.771     -43.254
C(item_nbr)[T.32]    -42.6786      2.790    -15.297      0.000     -48.147     -37.210
C(item_nbr)[T.33]     14.7915      2.939      5.032      0.000       9.031      20.552
C(item_nbr)[T.34]     -2.4640      4.787     -0.515      0.607     -11.846       6.918
C(item_nbr)[T.35]    -19.9878      2.646     -7.554      0.000     -25.174     -14.801
C(item_nbr)[T.36]     24.3524      2.192     11.112      0.000      20.057      28.648
C(item_nbr)[T.37]    -32.3438      2.041    -15.849      0.000     -36.344     -28.344
C(item_nbr)[T.38]    -21.1327      2.731     -7.739      0.000     -26.485     -15.780
C(item_nbr)[T.39]    -52.9863      3.244    -16.334      0.000     -59.344     -46.628
C(item_nbr)[T.40]    -19.2016      3.604     -5.328      0.000     -26.265     -12.138
C(item_nbr)[T.41]    -20.1987      2.205     -9.159      0.000     -24.521     -15.876
C(item_nbr)[T.42]    -27.3877      2.509    -10.914      0.000     -32.306     -22.469
C(item_nbr)[T.43]    -55.8575      4.915    -11.365      0.000     -65.491     -46.224
C(item_nbr)[T.44]     80.0217      1.946     41.121      0.000      76.208      83.836
C(item_nbr)[T.45]     30.2558      1.981     15.277      0.000      26.374      34.138
C(item_nbr)[T.46]    -52.2389      2.841    -18.385      0.000     -57.808     -46.670
C(item_nbr)[T.47]    -10.3415      2.786     -3.712      0.000     -15.803      -4.880
C(item_nbr)[T.48]     47.1373      2.521     18.697      0.000      42.196      52.079
C(item_nbr)[T.49]    -51.7365      2.911    -17.774      0.000     -57.442     -46.032
C(item_nbr)[T.50]    -31.5935      2.383    -13.258      0.000     -36.264     -26.923
C(item_nbr)[T.51]    -28.9297      2.381    -12.149      0.000     -33.597     -24.262
C(item_nbr)[T.52]    -50.6490      2.234    -22.669      0.000     -55.028     -46.270
C(item_nbr)[T.53]    -27.4392      2.685    -10.220      0.000     -32.701     -22.177
C(item_nbr)[T.54]    -30.6263      2.705    -11.323      0.000     -35.928     -25.325
C(item_nbr)[T.55]    -31.0086      2.603    -11.910      0.000     -36.111     -25.906
C(item_nbr)[T.56]    -19.5658      2.402     -8.145      0.000     -24.274     -14.858
C(item_nbr)[T.57]    -21.4743      2.910     -7.379      0.000     -27.178     -15.770
C(item_nbr)[T.58]    -20.5038      2.648     -7.743      0.000     -25.694     -15.314
C(item_nbr)[T.59]    -25.6407      2.525    -10.155      0.000     -30.589     -20.692
C(item_nbr)[T.60]   -103.3292      5.019    -20.587      0.000    -113.167     -93.492
C(item_nbr)[T.61]    -39.5269      2.236    -17.675      0.000     -43.910     -35.144
C(item_nbr)[T.62]    -32.3295      2.771    -11.666      0.000     -37.761     -26.898
C(item_nbr)[T.63]    -36.0122      2.839    -12.685      0.000     -41.576     -30.448
C(item_nbr)[T.64]    -69.1123      3.029    -22.814      0.000     -75.050     -63.175
C(item_nbr)[T.65]    -64.8763      2.653    -24.452      0.000     -70.076     -59.676
C(item_nbr)[T.66]    -25.6878      2.446    -10.501      0.000     -30.482     -20.893
C(item_nbr)[T.67]    -32.5850      2.418    -13.475      0.000     -37.325     -27.845
C(item_nbr)[T.68]      6.0193      2.039      2.952      0.003       2.023      10.016
C(item_nbr)[T.69]    -36.2828      2.642    -13.732      0.000     -41.462     -31.104
C(item_nbr)[T.70]     16.5547      3.057      5.415      0.000      10.563      22.546
C(item_nbr)[T.71]   -109.7662      2.820    -38.929      0.000    -115.293    -104.240
C(item_nbr)[T.72]    -22.3269      2.660     -8.394      0.000     -27.540     -17.114
C(item_nbr)[T.73]    -52.3309      2.781    -18.816      0.000     -57.782     -46.880
C(item_nbr)[T.74]    -52.4636      2.789    -18.812      0.000     -57.930     -46.997
C(item_nbr)[T.75]    -37.4975      2.961    -12.662      0.000     -43.302     -31.693
C(item_nbr)[T.76]   -103.4049      5.321    -19.432      0.000    -113.835     -92.975
C(item_nbr)[T.77]    -68.1200      2.857    -23.841      0.000     -73.720     -62.520
C(item_nbr)[T.78]    -28.8268      2.976     -9.686      0.000     -34.660     -22.994
C(item_nbr)[T.79]    -48.5076      2.765    -17.543      0.000     -53.927     -43.088
C(item_nbr)[T.80]    -25.6936      2.869     -8.954      0.000     -31.318     -20.070
C(item_nbr)[T.81]    -47.6700      2.608    -18.282      0.000     -52.781     -42.559
C(item_nbr)[T.82]    -28.1406      2.776    -10.138      0.000     -33.581     -22.700
C(item_nbr)[T.83]    -28.2653      2.428    -11.640      0.000     -33.025     -23.506
C(item_nbr)[T.84]    -42.0113      3.186    -13.185      0.000     -48.256     -35.766
C(item_nbr)[T.85]    -72.1612      3.118    -23.145      0.000     -78.272     -66.050
C(item_nbr)[T.86]    -38.6991      2.426    -15.949      0.000     -43.455     -33.943
C(item_nbr)[T.87]    -26.2384      2.562    -10.243      0.000     -31.259     -21.218
C(item_nbr)[T.88]    -17.2197      3.437     -5.011      0.000     -23.955     -10.484
C(item_nbr)[T.89]    -16.7036      4.145     -4.030      0.000     -24.828      -8.579
C(item_nbr)[T.90]    -95.6070      2.537    -37.690      0.000    -100.579     -90.635
C(item_nbr)[T.91]    -13.9385      2.707     -5.149      0.000     -19.244      -8.633
C(item_nbr)[T.92]   -102.9375      2.686    -38.320      0.000    -108.203     -97.672
C(item_nbr)[T.93]    -36.7283      2.005    -18.318      0.000     -40.658     -32.799
C(item_nbr)[T.94]    -31.7261      2.562    -12.385      0.000     -36.747     -26.705
C(item_nbr)[T.95]     -5.2607      2.652     -1.983      0.047     -10.459      -0.062
C(item_nbr)[T.96]    -96.2790      3.825    -25.169      0.000    -103.777     -88.781
C(item_nbr)[T.97]    -95.0896      3.646    -26.079      0.000    -102.236     -87.943
C(item_nbr)[T.98]    -47.6175      2.360    -20.181      0.000     -52.242     -42.993
C(item_nbr)[T.99]    -16.8987      3.095     -5.460      0.000     -22.965     -10.832
C(item_nbr)[T.100]   -24.8516      2.852     -8.714      0.000     -30.441     -19.262
C(item_nbr)[T.101]   -96.5850      2.986    -32.344      0.000    -102.438     -90.732
C(item_nbr)[T.102]   -38.1810      6.654     -5.738      0.000     -51.223     -25.139
C(item_nbr)[T.103]    15.5039      3.360      4.614      0.000       8.918      22.090
C(item_nbr)[T.104]   -32.4606      2.721    -11.930      0.000     -37.793     -27.128
C(item_nbr)[T.105]   -35.1997      2.604    -13.519      0.000     -40.303     -30.096
C(item_nbr)[T.106]   -38.2378      4.201     -9.103      0.000     -46.471     -30.005
C(item_nbr)[T.107]   -32.9542      2.998    -10.991      0.000     -38.831     -27.078
C(item_nbr)[T.108]   -34.8087      2.788    -12.485      0.000     -40.273     -29.344
C(item_nbr)[T.109]   -21.6668      2.362     -9.171      0.000     -26.297     -17.036
C(item_nbr)[T.110]   -18.7803      3.358     -5.593      0.000     -25.362     -12.199
C(item_nbr)[T.111]    17.0349      4.260      3.999      0.000       8.686      25.384
scale(cool)            1.2325      0.111     11.108      0.000       1.015       1.450
scale(heat)            2.2068      0.120     18.441      0.000       1.972       2.441
scale(preciptotal)     0.2062      0.091      2.261      0.024       0.027       0.385
scale(snowfall)       -0.2577      0.095     -2.708      0.007      -0.444      -0.071
is_holiday            10.0864      0.193     52.192      0.000       9.708      10.465
==============================================================================
Omnibus:                   398084.430   Durbin-Watson:                   1.881
Prob(Omnibus):                  0.000   Jarque-Bera (JB):     462615710143.088
Skew:                          59.252   Prob(JB):                         0.00
Kurtosis:                    9673.862   Cond. No.                         295.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
from sklearn.model_selection import KFold

trial = 4

cv = KFold(n_splits=trial, shuffle=True, random_state=2)

total = 0


for train_index, test_index in cv.split(X):
    print("test index :", test_index, len(test_index))
    print("." * 80)
    print("train index:", train_index, len(train_index))
    print("=" * 80)

    X_train = X.loc[train_index, :]
    X_test = X.loc[test_index, :]
    y_train = y.loc[train_index, :]
    y_test = y.loc[test_index, :]

    model = sm.OLS.from_formula(formula, data=pd.concat([X_train, y_train], axis=1))
    result = model.fit()
    
    y_hat = result.predict(X_test)
    
    ESS = ((y_hat - y_hat.mean())**2).sum()
    TSS = ((y_test-y_test.mean())**2).sum()
    total += ESS/TSS
    print(ESS/TSS)
    
total/trial

In [ ]:
res = result.resid_pearson
index = result.resid.index
outlier_index = abs(res) >= 2

row = pd.Series(index=index, data=res)
drop_index = row[outlier_index].index
len(drop_index)

tmp.drop(list(drop_index),inplace=True)
tmp.reset_index(drop = True, inplace = True)

X = tmp.loc[:, ['store_nbr', 'item_nbr', 'cool', 'heat', 'preciptotal','snowfall', 'is_holiday']]
y = tmp.loc[:, ['units']]

In [ ]:
from sklearn.model_selection import KFold

trial = 4

cv = KFold(n_splits=trial, shuffle=True, random_state=2)

total = 0


for train_index, test_index in cv.split(X):
    print("test index :", test_index, len(test_index))
    print("." * 80)
    print("train index:", train_index, len(train_index))
    print("=" * 80)

    X_train = X.loc[train_index, :]
    X_test = X.loc[test_index, :]
    y_train = y.loc[train_index, :]
    y_test = y.loc[test_index, :]

    model = sm.OLS.from_formula(formula, data=pd.concat([X_train, y_train], axis=1))
    result = model.fit()
    
    y_hat = result.predict(X_test)
    
    ESS = ((y_hat - y_hat.mean())**2).sum()
    TSS = ((y_test-y_test.mean())**2).sum()
    total += ESS/TSS
    print(ESS/TSS)
    
total/trial

In [ ]:
res = result.resid_pearson
index = result.resid.index
outlier_index = abs(res) >= 2

row = pd.Series(index=index, data=res)
drop_index = row[outlier_index].index
len(drop_index)

tmp.drop(list(drop_index),inplace=True)
tmp.reset_index(drop = True, inplace = True)

X = tmp.loc[:, ['store_nbr', 'item_nbr', 'cool', 'heat', 'preciptotal','snowfall', 'is_holiday']]
y = tmp.loc[:, ['units']]

In [ ]:
from sklearn.model_selection import KFold

trial = 4

cv = KFold(n_splits=trial, shuffle=True, random_state=2)

total = 0


for train_index, test_index in cv.split(X):
    print("test index :", test_index, len(test_index))
    print("." * 80)
    print("train index:", train_index, len(train_index))
    print("=" * 80)

    X_train = X.loc[train_index, :]
    X_test = X.loc[test_index, :]
    y_train = y.loc[train_index, :]
    y_test = y.loc[test_index, :]

    model = sm.OLS.from_formula(formula, data=pd.concat([X_train, y_train], axis=1))
    result = model.fit()
    
    y_hat = result.predict(X_test)
    
    ESS = ((y_hat - y_hat.mean())**2).sum()
    TSS = ((y_test-y_test.mean())**2).sum()
    total += ESS/TSS
    print(ESS/TSS)
    
total/trial

In [ ]:
print(result.summary())