In [34]:
import numpy as np
import pandas as pd

In [35]:
weather = pd.read_csv('../data/basic/weather.csv', index_col=['station_nbr'])

In [36]:
print(weather.shape)
weather.loc[5].head()    # all missing data

(20517, 19)

,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,sunrise,sunset,codesum,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed
station_nbr,,,,,,,,,,,,,,,,,,,
5,2012-06-01,M,M,M,M,M,M,M,M,0411,1913,,M,M,M,M,M,M,M
5,2012-06-02,M,M,M,M,M,M,M,M,0411,1914,,M,M,M,M,M,M,M
5,2012-06-03,M,M,M,M,M,M,M,M,0410,1915,,M,M,M,M,M,M,M
5,2012-06-04,M,M,M,M,M,M,M,M,0410,1915,,M,M,M,M,M,M,M
5,2012-06-05,M,M,M,M,M,M,M,M,0409,1916,,M,M,M,M,M,M,M

In [37]:
weather = weather.drop(5)    # drop station_5
print(weather.shape)
weather.tail()

(19665, 19)

,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,sunrise,sunset,codesum,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed
station_nbr,,,,,,,,,,,,,,,,,,,
16,2014-10-31,53,34,44,M,35,41,21,0,-,-,,M,0.00,29.90,29.99,4.5,03,5.3
17,2014-10-31,59,34,47,M,32,41,18,0,-,-,RA,0.0,0.00,29.72,30.39,9.2,01,9.3
18,2014-10-31,67,49,58,-4,40,50,7,0,0644,1738,,0.0,0.00,29.78,30.28,10.6,36,11.2
19,2014-10-31,45,33,39,-6,24,32,26,0,0624,1646,RA SN,0.1,0.02,29.51,30.24,20.4,34,20.9
20,2014-10-31,68,50,59,M,39,50,6,0,-,-,,0.0,0.00,29.57,30.27,10.5,36,11.2

# sunrise, sunset conversion to numerical value

In [38]:
def converge_sun(sun):
    if sun != '-':
        return float(sun[:2]) * 60 + float(sun[2:4])

In [39]:
weather['sunrise'] = weather['sunrise'].apply(converge_sun)
weather['sunset'] = weather['sunset'].apply(converge_sun)

In [42]:
weather['sunrise'].head()

station_nbr
1      NaN
2    436.0
3    455.0
4    448.0
6    447.0
Name: sunrise, dtype: float64

In [43]:
weather['sunset'].head()

station_nbr
1       NaN
2     986.0
3    1040.0
4    1062.0
6    1062.0
Name: sunset, dtype: float64

# replace missing value with np.nan

In [44]:
for i in weather.columns:
    print(i, "\n", weather[i].unique())

date
 ['2012-01-01' '2012-01-02' '2012-01-03' ..., '2014-10-29' '2014-10-30'
 '2014-10-31']
tmax
 ['52' '48' '55' '63' '50' '66' '34' '73' '72' '38' '56' '59' '46' '45' '60'
 '44' '21' '65' '43' '53' '25' '32' '28' '62' '61' '47' '30' '26' '71' '58'
 '39' '54' '23' '27' '31' '68' '70' '67' '36' '69' '74' '75' '33' '51' '57'
 '41' '49' '76' '35' '77' '64' '40' '16' '37' '42' '14' '22' '13' '10' '20'
 '24' '80' '4' '11' '78' '17' '18' '79' '29' '81' '82' '83' '88' '87' '92'
 '89' '84' '85' '86' '90' '91' '94' '93' '96' '95' 'M' '97' '98' '101' '99'
 '100' '105' '103' '102' '106' '104' '109' '107' '108' '110' '111' '112'
 '114' '113' '19' '15' '12' '-1' '5' '8' '9' '1' '6' '2' '3' '7' '-2' '-11'
 '-4' '-6' '0']
tmin
 ['31' '33' '34' '47' '45' '19' '53' '48' '18' '26' '30' '38' '40' '25' '41'
 '28' '24' '37' '36' '11' '16' '29' '22' '35' '15' '9' '21' '27' '10' '5'
 '32' '20' '3' '8' '44' '46' '17' '55' '43' '57' '50' '49' '54' '42' '39'
 '52' '23' '56' '14' '59' '-1' '12' '6' '4' '2' '60' '51' '63' '-5' '7'
 '61' '13' '-11' '0' '-2' '58' '-7' '62' '66' '67' '64' '65' '69' '68' '70'
 '71' '73' '72' '75' '74' '76' '78' 'M' '77' '79' '80' '83' '81' '82' '86'
 '88' '85' '84' '1' '-3' '-6' '-9' '-4' '-10' '-8' '-13' '-12' '-17' '-19'
 '-21' '-14' '-16' '-15']
tavg
 ['42' '41' '45' '55' '49' 'M' '27' '63' '60' '28' '37' '40' '47' '50' '32'
 '35' '16' '52' '56' '33' '36' '34' '44' '20' '43' '22' '19' '38' '18' '13'
 '57' '51' '30' '46' '29' '26' '48' '31' '65' '54' '58' '24' '61' '62' '59'
 '53' '64' '25' '39' '67' '68' '14' '11' '10' '8' '5' '17' '66' '15' '-3'
 '23' '21' '7' '9' '70' '69' '72' '71' '12' '73' '75' '74' '76' '79' '78'
 '77' '80' '81' '82' '83' '84' '85' '87' '86' '90' '88' '89' '93' '92' '91'
 '95' '94' '97' '99' '96' '100' '98' '6' '3' '-5' '2' '4' '1' '-4' '0' '-2'
 '-1' '-10' '-16' '-8' '-6' '-7']
depart
 ['M' '16' ' 9' ' 4' ' 0' ' 7' ' 5' '10' '12' '-1' '-2' '-4' '15' '-6' ' 2'
 '-5' '-18' '-3' '-11' '11' ' 6' '-15' '-8' ' 8' '14' '19' ' 1' '24' '23'
 '13' ' 3' '17' '22' '-9' '-10' '28' '25' '-7' '20' '-13' '21' '18' '26'
 '-17' '-16' '-14' '-20' '27' '-12' '31' '29' '32' '33' '-22' '-23' '-21'
 '30' '-19' '-24' '-27' '-25' '-26' '-28' '-32' '-31' '-35']
dewpoint
 ['36' '37' '24' '28' '31' '26' '34' '17' '55' '54' '12' '25' '35' '23' '11'
 '27' '29' '8' '33' '16' '10' '9' '21' '4' '19' '22' '2' '6' '18' '5' '-1'
 '0' '39' '41' '45' '15' '32' '13' '43' '46' '38' '52' '53' '44' '40' '47'
 '51' '48' '20' '49' '50' '14' '56' '30' '3' '7' 'M' '-5' '-3' '42' '-7'
 '59' '61' '57' '-15' '58' '60' '62' '64' '66' '-2' '65' '63' '67' '68'
 '69' '70' '71' '72' '74' '73' '75' '1' '-4' '-13' '-10' '-11' '-8' '-12'
 '-6' '-9' '76' '77' '-14' '-17' '-24' '-20' '-19' '-16']
wetbulb
 ['40' '39' '36' '43' '35' '46' '23' '58' '56' '57' '21' '38' '37' '30' '32'
 '28' '29' '15' '44' '17' '18' '16' '31' '33' '14' '11' '47' '45' '49' '26'
 '41' '25' '50' '52' '22' '42' 'M' '48' '53' '54' '51' '27' '55' '20' '34'
 '60' '59' '12' '10' '19' '13' '7' '5' '2' '62' '63' '64' '24' '61' '-4'
 '6' '4' '9' '65' '66' '67' '8' '68' '69' '70' '71' '72' '73' '74' '75'
 '76' '77' '78' '3' '-5' '-3' '0' '1' '79' '80' '-2' '-8' '-15' '-10' '-6'
 '-9' '-7' '-1']
heat
 ['23' '24' '20' '10' '16' 'M' '38' '2' '5' '37' '28' '25' '18' '15' '33'
 '30' '49' '13' '9' '32' '29' '31' '21' '45' '22' '43' '46' '27' '47' '52'
 '8' '14' '35' '19' '36' '39' '17' '34' '0' '11' '7' '41' '4' '3' '6' '12'
 '1' '40' '26' '51' '54' '55' '57' '60' '48' '50' '68' '42' '44' '58' '56'
 '53' '59' '62' '70' '63' '61' '64' '69' '65' '67' '66' '75' '81' '73' '71'
 '72']
cool
 [' 0' 'M' ' 2' ' 3' ' 1' ' 5' ' 4' ' 7' ' 6' ' 8' '10' ' 9' '11' '14' '13'
 '12' '15' '16' '17' '18' '19' '20' '22' '21' '25' '23' '24' '28' '27' '26'
 '30' '29' '32' '34' '31' '35' '33']
sunrise
 [  nan  436.  455.  448.  447.  443.  444.  459.  438.  450.  460.  451.
  445.  449.  442.  437.  435.  441.  454.  434.  440.  433.  458.  439.
  453.  432.  452.  457.  431.  430.  446.  456.  429.  428.  427.  426.
  425.  424.  423.  422.  421.  420.  419.  418.  417.  416.  414.  415.
  413.  412.  411.  409.  410.  408.  407.  405.  406.  404.  403.  401.
  400.  398.  397.  402.  396.  395.  394.  399.  393.  392.  391.  389.
  388.  387.  386.  385.  384.  379.  380.  383.  382.  381.  378.  377.
  376.  375.  374.  373.  372.  371.  370.  369.  368.  367.  366.  365.
  364.  363.  362.  360.  359.  358.  357.  355.  361.  390.  353.  352.
  351.  350.  348.  354.  346.  344.  343.  341.  347.  339.  345.  337.
  338.  336.  334.  332.  330.  331.  329.  327.  325.  326.  323.  324.
  322.  320.  318.  319.  316.  317.  315.  313.  314.  356.  311.  312.
  310.  308.  309.  306.  307.  305.  349.  303.  304.  301.  300.  298.
  299.  296.  302.  295.  342.  293.  340.  292.  290.  289.  291.  287.
  286.  288.  284.  333.  283.  285.  281.  280.  282.  279.  277.  328.
  276.  278.  335.  275.  273.  272.  271.  270.  268.  321.  267.  266.
  269.  265.  264.  263.  262.  261.  260.  259.  258.  257.  256.  255.
  254.  253.  252.  251.  250.  249.  248.  247.  246.  274.  294.  297.]
sunset
 [   nan   986.  1040.  1062.  1058.  1057.  1049.   981.  1052.   988.
   987.  1041.   982.  1053.   989.  1063.  1059.  1050.   983.  1054.
   990.  1042.  1064.  1060.  1051.   984.   991.  1043.  1065.   985.
  1055.  1044.  1061.  1056.   992.  1045.  1066.   993.  1046.  1067.
   995.   994.  1047.  1068.   996.  1069.   997.  1048.   998.  1070.
   999.  1071.  1000.  1072.  1001.  1073.  1002.  1074.  1004.  1003.
  1075.  1005.  1006.  1076.  1007.  1077.  1008.  1078.  1010.  1009.
  1079.  1011.  1080.  1012.  1081.  1014.  1015.  1016.  1082.  1017.
  1083.  1019.  1018.  1084.  1020.  1085.  1021.  1086.  1023.  1087.
  1024.  1088.  1025.  1027.  1089.  1022.  1028.  1090.  1029.  1091.
  1031.  1092.  1026.  1032.  1093.  1033.  1094.  1035.  1030.  1036.
  1034.  1095.  1037.  1096.  1039.  1097.  1038.  1098.  1099.  1100.
  1101.  1102.  1103.  1104.  1105.  1106.  1107.  1108.  1109.  1110.
  1111.  1112.  1113.  1114.  1115.  1116.  1117.  1118.  1119.  1120.
  1121.  1122.  1123.  1124.  1125.  1126.  1127.  1128.  1129.  1130.
  1131.  1132.  1133.  1134.  1135.  1136.  1137.  1138.  1139.  1140.
  1141.  1142.  1143.  1144.  1145.  1146.  1147.  1148.  1149.  1150.
  1151.  1152.  1153.  1154.  1155.  1156.  1157.  1158.  1159.  1160.
  1161.  1162.  1163.  1164.  1165.  1166.  1167.  1168.  1169.  1170.
  1171.  1172.  1173.  1174.  1175.  1176.  1177.  1178.  1179.  1180.
  1181.  1182.  1183.  1184.  1185.  1186.  1187.  1188.  1189.  1013.
   980.   979.   978.   977.   976.   975.   974.   973.   972.   971.]
codesum
 ['RA FZFG BR' 'RA' ' ' 'RA BR' 'UP' 'FG+ FG BR' 'RA FG+ FZFG BR'
 'RA MIFG BR' 'RA SN BR' 'SN UP' 'BR' 'SN' 'BR HZ' 'FG+ BR'
 'SN FG+ FZFG BR' 'RA HZ' 'RA BR HZ' 'FG BR' 'TSRA FG+ BR HZ'
 'RA BR HZ VCTS' 'TSRA RA DZ BR' 'TSRA RA DZ BR VCTS' 'TSRA RA BR'
 'RA BR VCTS' 'SN BR' 'TS TSRA RA DZ BR' 'SN FZFG BR'
 'RA SN FG+ FG FZFG BR UP' 'SN FZFG BR UP' 'DZ SN BR HZ'
 'RA FZRA FG+ FG BR UP' 'FZRA FG+ FZFG UP' 'FZRA SN BR UP' 'RA FG BR'
 'SN BR HZ' 'RA SN BR HZ' 'RA SN FG+ BR' 'DZ BR HZ' 'RA SN FG BR'
 'RA SN BR HZ BLSN' 'FZDZ BR' 'FG+ FG BR HZ' 'FG+ FG BCFG BR' 'FG+'
 'SN FZFG' 'BR HZ DU' 'DZ BR' 'BR HZ BLDU' 'FG+ BR HZ' 'RA FG+ FG BR'
 'BR HZ DU SQ' 'HZ DU' 'BR DU' 'DZ FZDZ BR' 'RA SN FG+ FG BR' 'BLDU'
 'FG+ FG' 'DU' 'TS RA BR HZ' 'BCFG BR' 'FG+ FG FZFG BR' 'RA DZ BR'
 'TS TSRA BR' 'TSRA RA DZ VCTS' 'RA FZRA SN BR UP' 'FZRA SN FG+ FZFG BR UP'
 'MIFG' 'SN BR UP HZ' 'RA FZRA BR' 'DZ' 'RA BCFG BR' 'HZ'
 'RA FG+ FG FZFG BR HZ' 'RA DZ FG+ BCFG BR' 'DZ FG BR HZ'
 'FG+ FZFG BR UP HZ' 'RA FG+ FZFG BR HZ' 'BCFG BR HZ'
 'RA DZ FG+ FG BR HZ VCTS' 'TSRA RA' 'TS RA BR VCTS' 'SN FZFG BR BLSN'
 'TS RA DZ BR' 'TSRA RA BR VCTS' 'TS RA BR' 'RA VCTS' 'RA DZ' 'RA DZ BR HZ'
 'FG+ FZFG BR' 'SN BR HZ BLSN' 'PL' 'DZ SN' 'DZ FZDZ SN BR'
 'FZRA SN FG+ FZFG BR' 'RA DZ FG BR' 'FZDZ SN BR' 'RA DZ SN FG BR'
 'DZ FG+ BCFG BR' 'DZ FG+ FG FZFG BR' 'RA UP' 'TSRA RA FG BR HZ'
 'DZ FG+ BR' 'RA FG+ BR' 'RA BR UP' 'TSRA' 'RA SN' 'FG+ BCFG BR HZ'
 'TS FG BR' 'FZFG BR' 'RA SN FG+ BR UP' 'SN BR UP' 'RA SN BR UP' 'SN FG BR'
 'RA DZ SN BR' 'FZRA SN FZFG BR' 'RA SN FG BR UP' 'SN FG+ FZFG BR UP'
 'RA FZRA FG+ FG FZFG BR' 'RA FZRA SN FZFG BR UP' 'FU' 'FZRA FZDZ SN BR'
 'RA DZ HZ' 'RA MIFG' 'RA DZ BR VCTS' 'RA DZ HZ VCTS' 'TSRA RA DZ FG BR'
 'TSRA RA DZ HZ' 'BR VCFG' 'TS' 'TS MIFG BR' 'MIFG BR' 'TSRA RA FG BR'
 'TSRA BR' 'BCFG' 'TSRA RA BR HZ' 'TSRA RA FG+ BR' 'DZ FG BR'
 'DZ FG+ FG BR' 'FG BCFG BR' 'TS FG+ FG BR' 'HZ FU' 'TS TSRA RA'
 'TS TSRA RA FG BR' 'TSRA RA BR SQ' 'HZ VCTS' 'TS RA HZ VCTS'
 'TS FG+ BR HZ' 'BR HZ VCTS' 'FG BR HZ' 'BR HZ FU' 'BR FU' 'RA BCFG BR HZ'
 'TS TSRA BR HZ' 'TS TSRA RA BR' 'TS VCTS' 'TSRA BR HZ' 'RA DZ VCTS'
 'TS RA' 'TSRA BR VCTS' 'VCTS' 'TS TSRA' 'TSRA RA VCTS' 'DZ HZ' 'TSRA VCTS'
 'TS BR' 'TS RA HZ FU' 'TS TSRA RA BR HZ FU' 'TSRA RA FG+ BR VCTS'
 'TSRA BR FU' 'TS TSRA RA DZ' 'MIFG FU' 'DZ BR HZ VCTS' 'TSRA HZ'
 'TSRA RA DZ BR HZ' 'TS BR FU' 'TS TSRA RA BCFG BR' 'RA BR FU'
 'TSRA RA FG BR VCTS' 'TS FU' 'RA FG BR HZ' 'TS TSRA VCTS'
 'TS TSRA RA BR VCTS' 'RA FG+ FG BR HZ VCTS' 'TS TSRA RA VCTS'
 'TS GR RA BR VCTS' 'BR VCTS' 'RA FG+ FG' 'RA DZ BR HZ VCTS'
 'RA FG+ BR HZ VCTS' 'TS RA VCTS' 'FG+ BCFG BR' 'TS RA FG' 'TS HZ VCTS'
 'RA FG+ BR VCTS' 'TS HZ' 'TS TSRA RA BR HZ' 'TS FG+ BR' 'RA BLDU SQ'
 'TS RA HZ' 'FG' 'TSRA RA BCFG BR HZ' 'TSRA FG+' 'RA HZ VCTS' 'TSRA RA SQ'
 'TSRA BR HZ VCTS' 'TS TSRA RA HZ' 'TS RA GS BR' 'RA FG BCFG BR'
 'RA DZ FG+ BR HZ' 'RA FG+' 'TSRA RA FG+ FG BR' 'DZ SN BR' 'DZ FG+ BR HZ'
 'TS RA DZ VCTS' 'TS RA BR HZ VCTS' 'RA SN FZFG BR' 'FZFG' 'RA SN BR UP HZ'
 'TS TSSN RA FG+ FG BR VCTS' 'TSSN RA SN FG+ FZFG BR' 'MIFG BR HZ'
 'FG+ FZFG' 'RA DZ BCFG BR' 'SN FG+ FG BR' 'FZRA SN BR'
 'RA FZRA FG+ FG FZFG BR UP' 'RA DZ FG+ BR' 'DZ SN FG+ FG BR UP'
 'RA FG+ FG BR UP' 'TSRA RA HZ VCTS' 'TS TSRA RA FG+ FG BR'
 'FZRA FG+ FZFG BR HZ' 'FG+ FZFG BCFG' 'RA FZRA SN BR'
 'RA FZRA SN FG+ FG FZFG BR' 'TS HZ BLDU' 'FZRA SN UP HZ' 'UP HZ'
 'TS TSRA RA SN FG BR' 'RA SN FG+ FZFG BR HZ' 'DZ SN FG BR' 'SN HZ'
 'RA SN FG FZFG BR' 'RA DZ SN FG+ BR' 'TSRA RA BCFG BR'
 'TSRA RA DZ SN FG HZ' 'RA FG+ FG MIFG BR' 'RA FG+ BR UP' 'DZ MIFG BR'
 'FG+ MIFG BR' 'FG MIFG BR' 'RA FZRA' 'FZRA' 'RA DZ SN' 'SG' 'BR UP HZ'
 'TS SN GS' 'FZRA SN FZFG BR UP' 'SN BLSN' 'FZRA PL BR HZ' 'BR UP'
 'FZRA FG+ FG FZFG BR UP' 'TSRA RA BR HZ VCTS' 'TSRA RA DZ'
 'RA FZRA FG+ BR' 'SN UP BLSN' 'SN HZ BLSN' 'RA FG+ FG BR HZ'
 'RA SN PL BR HZ' 'SN FG+ FZFG BR UP HZ' 'SN FG+ FG FZFG BR UP' 'SN UP HZ'
 'SN FG+ FZFG HZ' 'TS DZ BR' 'RA FZRA SN BR UP HZ' 'TSRA DZ BR'
 'RA FZRA SN FG+ FG FZFG BR UP' 'RA SN FG+ FG BR HZ' 'FG+ FZFG BR HZ'
 'SN BR UP BLSN' 'RA SN PL FG+ BR' 'RA SN FG+ FG BR UP'
 'TS TSRA RA DZ FZRA PL BR' 'TS TSRA RA FZRA BR' 'SN FZFG BR HZ'
 'TSRA RA FZRA BR UP VCTS' 'FZRA SN FG BR' 'SN FG+ FZFG BR BLSN'
 'TS TSRA RA SN PL BR' 'RA FZRA SN FG BR UP HZ VCTS' 'RA SN BR VCTS'
 'SN FG BR UP' 'SN FG+ FG FZFG BR' 'BCFG HZ' 'FZRA SN BR UP HZ'
 'RA SN FG FZFG BR UP' 'TSRA DZ HZ' 'RA SN UP' 'TS TSRA RA FG BR VCTS'
 'TS TSSN RA DZ SN BR' 'RA DZ SN BR HZ' 'TSSN RA DZ SN BR VCTS'
 'RA FZRA BR UP HZ' 'SN BR BLSN BLDU' 'RA FZRA BR VCTS' 'TSRA RA FZRA BR'
 'BR SQ' 'TS TSRA RA FG+ BR HZ VCTS' 'FZDZ SN FZFG BR' 'RA DZ FG BCFG BR'
 'TSRA RA DZ SN BR HZ VCTS' 'TSSN FG+ BR VCTS' 'TS TSRA FG+ BR HZ'
 'TS TSRA BR SQ' 'RA FG+ FG BR VCTS' 'TS RA FG+ BR HZ VCTS'
 'TS RA DZ BR HZ' 'TS TSRA GR RA BR' 'TSRA FG+ FG BR VCTS' 'TS TSRA DZ BR'
 'TS RA FG BR' 'TS TSRA RA FG+ FG VCTS' 'TS TSRA RA FG+'
 'TSRA TSSN BR HZ VCTS' 'DZ FG+ FG HZ' 'TS TSRA BR HZ VCTS' 'RA FG+ BR HZ'
 'TS BR HZ' 'TSRA BR SQ' 'RA FG BR VCTS' 'RA FG BR HZ VCTS' 'TS BR VCTS'
 'FG+ FG BR VCTS' 'TS RA FG+ BR' 'FG BR VCTS' 'TS SQ' 'VCFG' 'TS RA DZ'
 'TS RA DZ BR VCTS' 'RA FG+ FG BCFG BR' 'MIFG BCFG BR' 'TS RA GS'
 'RA FG MIFG BR' 'TSRA BCFG BR' 'RA DZ SN VCTS' 'RA FZFG BR HZ'
 'RA MIFG BCFG BR' 'FG+ FG MIFG BR' 'RA DZ FG+ FG BR HZ' 'RA FZRA BR HZ'
 'TS RA DZ HZ VCTS' 'RA FG BR HZ SQ' 'RA DZ FZRA FZDZ BR' 'FZRA UP'
 'FZRA BR UP' 'RA FZRA BR UP' 'RA SN FG+' 'SN PL' 'RA PL' 'DZ FZRA'
 'FZRA BR HZ' 'RA DZ SN HZ' 'RA FZRA SN FG+ BR UP' 'SN FG+ FG BR HZ'
 'RA DZ FG+ FG BR' 'RA DZ FG+ MIFG BR HZ' 'DZ FG+' 'FZRA SN UP'
 'RA FZRA FZDZ PL BR' 'FZRA BR' 'RA PL BR' 'FZDZ' 'FZDZ BR HZ'
 'PRFG BCFG BR HZ' 'RA FZRA SN BR HZ' 'SN BR BLSN' 'RA DZ FZRA BR HZ'
 'FZRA BR UP HZ' 'DZ FZRA FZDZ SN BR' 'DZ SN FG+ FZFG BR'
 'RA FZRA FG+ FZFG BR UP' 'RA FZRA FG+ FG BR' 'SN FG+ FZFG BR HZ' 'BLSN'
 'FZDZ SN BLSN' 'RA FG+ BCFG BR' 'SN FG+ BR HZ' 'TSRA FG+ FG BR'
 'SN FG FZFG BR' 'SN FZFG UP' 'RA FZRA SN UP' 'RA FZRA PL BR' 'RA DZ UP'
 'FZRA PL' 'RA FZRA UP' 'SN FZFG BLSN' 'FG+ FG FZFG BR HZ' 'FZFG BR HZ'
 'SN FG+ FZFG' 'RA DZ BR UP HZ' 'RA BR UP HZ' 'FZRA SN FZFG BR UP HZ'
 'RA FG+ BCFG BR HZ' 'RA DZ FZRA FZDZ SN FG+ FG BR HZ' 'SN FG+ FZFG UP'
 'DZ FZDZ BR HZ' 'RA DZ BR UP' 'GS BR HZ' 'FZDZ FG BR HZ' 'RA DZ FZDZ BR'
 'RA SN FG+ FZFG BR' 'RA SN FG+ FG FZFG BR' 'UP BLSN'
 'FZRA SN FG+ FZFG BR HZ' 'HZ BLDU' 'TSRA RA SN FG+ BR HZ'
 'RA FG+ FZFG BR UP' 'TSRA RA FG+ FG BR UP' 'FZRA FZDZ BR'
 'RA FZRA FG+ FG BR HZ' 'RA DZ FZDZ FG+ BR' 'TS FZDZ SN BR BLSN'
 'FZRA SN VCTS' 'RA DZ SN BR UP' 'TS FZDZ SN BLSN'
 'FZRA SN FZFG BR UP BLSN' 'RA DZ FZDZ SN PL BR' 'TS TSRA FZRA'
 'TS RA FZRA BR VCTS' 'TSSN UP VCTS' 'TSSN SN BR UP' 'RA PL HZ'
 'RA FZRA FG BR HZ' 'FZRA FG FZFG BR' 'RA DZ SN FG FZFG BR'
 'TS TSRA GR RA BR HZ SQ' 'TSSN BR' 'TSRA RA FG' 'RA DU' 'TSRA RA SN BR'
 'TS TSRA FG+ BR' 'TSRA FG BR' 'DZ BR VCTS' 'TS TSRA HZ' 'TSRA FG+ BR'
 'TS TSRA BR VCTS' 'TS RA FG+ FG BR VCTS' 'TS TSRA RA DZ FG+ FG BR VCTS'
 'TSRA DZ BR VCTS']
snowfall
 ['M' '0.0' '0.5' '  T' '0.2' '3.6' '3.7' '6.1' '0.6' '0.3' '2.0' '1.2'
 '1.4' '2.3' '1.3' '1.0' '4.3' '0.1' '1.7' '0.7' '1.9' '0.9' '0.4' '1.6'
 '4.7' '4.0' '2.1' '7.1' '4.2' '1.8' '5.2' '0.8' '1.5' '2.8' '3.0' '5.0'
 '9.3' '2.6' '3.1' '4.4' '3.4' '1.1' '5.5' '15.2' '7.8' '13.5' '16.2' '3.5'
 '2.2' '3.2' '13.1' '4.6' '2.4' '5.4' '7.2' '14.9' '7.7' '11.0' '2.9' '5.1'
 '3.3' '3.9' '7.0' '6.6' '8.0' '4.9' '6.2' '6.4' '4.1' '5.8' '2.7' '12.2'
 '10.5' '6.7' '3.8' '5.7' '2.5']
preciptotal
 ['0.05' '0.07' '0.00' '  T' '0.09' '0.12' '0.01' '0.02' '0.16' '0.03'
 '0.13' '0.87' '0.62' '1.32' '1.58' '0.49' '0.30' '0.04' '0.69' '1.06'
 '0.34' '0.98' '0.35' '0.11' '0.06' '0.15' '0.08' '0.22' '0.14' '0.20'
 '0.25' '0.31' '0.17' '0.24' '0.40' '0.82' '1.52' '1.44' '1.75' '0.52'
 '3.14' '5.67' '3.00' '0.71' '3.06' '2.61' '0.21' '0.23' '0.19' '1.14'
 '1.20' '1.15' '0.38' '0.48' '0.84' '0.91' '1.33' '0.67' '1.70' '0.10'
 '0.27' '0.18' '0.53' '0.59' '0.70' '1.72' '1.10' '1.56' '1.82' '0.77'
 '1.04' '0.80' '0.50' '0.56' '0.51' '0.58' '0.47' '0.54' '0.61' '0.81'
 '0.64' '0.65' '0.45' '0.36' '0.33' '1.27' '1.08' '0.96' '0.86' '1.01'
 '0.28' '0.39' '1.39' '0.42' '0.90' '2.81' '2.34' '0.89' '3.02' '3.05'
 '2.40' '2.85' '1.43' '2.77' '2.69' '2.16' '1.07' '2.09' '2.05' '0.46'
 '0.32' '1.18' '0.75' '0.60' '1.30' '0.73' '0.88' '2.75' '0.93' '0.26'
 '0.78' '1.19' '0.92' '1.00' '0.68' '0.63' '1.05' '0.85' '1.67' '1.36'
 '1.23' '1.90' '0.83' '1.28' '0.76' '0.79' '2.45' '0.43' '0.44' '2.70'
 '1.17' '2.84' '0.37' '1.64' '0.95' '0.72' '1.12' '2.15' '1.78' '2.68'
 '1.09' '2.83' '1.40' '1.81' '1.96' '0.41' '3.32' '0.29' '2.10' '1.71'
 '0.99' '2.21' '1.66' '1.45' '5.12' '3.47' '2.91' '0.66' '1.99' '1.47'
 '1.22' '0.57' '4.65' '7.36' '6.93' '4.84' '5.20' '5.36' '1.11' '1.38'
 '1.24' '1.53' '2.23' '1.03' '0.55' 'M' '1.55' '2.50' '2.27' '2.04' '2.35'
 '1.21' '1.16' '3.91' '1.37' '1.95' '1.35' '1.41' '1.29' '1.42' '0.94'
 '3.52' '1.91' '2.38' '3.34' '2.37' '2.56' '1.49' '1.98' '2.65' '1.89'
 '1.85' '0.74' '0.97' '1.80' '3.20' '1.57' '1.79' '3.19' '2.31' '2.03'
 '2.57' '1.34' '1.13' '1.50' '2.42' '3.03' '2.06' '1.88' '2.82' '2.92'
 '3.30' '3.13' '5.59' '5.65' '2.00' '2.18' '1.94' '2.28' '1.69' '2.60'
 '2.12' '1.92' '1.73' '1.76' '1.63' '2.48' '3.53' '2.13' '1.60' '1.02'
 '1.61' '1.65' '1.68' '1.31' '2.20' '2.76' '1.46' '1.54' '1.25' '2.02'
 '4.22' '3.16' '3.24' '2.49' '2.11' '1.83' '1.93' '1.87' '2.01' '1.62'
 '3.27' '3.07' '2.14' '2.07' '2.59' '3.17' '2.32' '1.26' '2.88' '1.77'
 '2.41' '3.66' '3.45' '5.04']
stnpressure
 ['29.78' '28.82' '29.77' '29.79' '29.95' '29.15' '30.05' '29.34' '30.16'
 '30.15' '24.60' '29.13' '29.53' '29.80' '29.83' '29.98' '29.06' '29.44'
 '28.51' '29.89' '29.93' '30.09' '29.23' '30.25' '29.67' '30.11' '30.10'
 '24.55' '29.21' '29.20' '29.48' '29.96' '29.47' '29.90' '28.69' '29.55'
 '29.70' '29.88' '28.84' '30.12' '29.26' '30.27' '30.26' '24.40' '29.61'
 '29.84' '29.43' '29.63' '29.86' '28.87' '29.72' '28.90' '30.35' '30.34'
 '24.49' '28.89' '29.59' '29.75' '29.54' '28.70' '29.35' '29.51' '29.68'
 '28.71' '29.87' '28.95' '30.20' 'M' '30.18' '24.26' '29.42' '29.66'
 '29.02' '29.46' '29.16' '29.65' '29.00' '30.14' '24.21' '28.50' '29.39'
 '29.19' '29.57' '28.63' '29.36' '24.19' '28.66' '29.60' '29.41' '29.32'
 '29.27' '29.45' '29.31' '28.78' '29.64' '30.17' '24.32' '28.76' '29.50'
 '29.56' '30.06' '29.05' '29.33' '28.79' '29.17' '30.13' '24.37' '28.77'
 '29.81' '29.52' '29.69' '28.74' '29.24' '30.03' '30.02' '24.13' '29.22'
 '29.14' '29.91' '28.92' '29.08' '29.10' '29.28' '28.47' '28.99' '24.24'
 '28.45' '28.85' '29.62' '28.62' '28.72' '28.30' '29.94' '30.04' '24.23'
 '29.11' '29.58' '28.64' '28.83' '29.99' '28.81' '29.73' '29.38' '29.29'
 '28.61' '30.36' '24.01' '29.85' '30.29' '29.03' '29.49' '28.41' '30.42'
 '30.41' '23.98' '30.32' '29.01' '30.24' '30.22' '29.40' '24.05' '28.48'
 '30.08' '23.95' '29.12' '29.30' '28.46' '24.06' '29.04' '28.56' '23.75'
 '28.27' '30.07' '23.93' '28.80' '29.97' '29.25' '29.18' '28.59' '30.00'
 '30.01' '24.16' '28.58' '29.07' '24.29' '24.36' '28.88' '24.31' '30.37'
 '24.10' '30.33' '29.71' '30.21' '24.27' '28.65' '30.23' '24.39' '28.55'
 '24.51' '28.97' '28.96' '29.82' '28.86' '24.30' '24.43' '29.92' '28.53'
 '28.94' '28.91' '28.54' '24.17' '29.74' '29.37' '28.68' '24.14' '23.89'
 '24.00' '24.03' '29.09' '28.22' '23.85' '28.40' '28.25' '24.08' '28.23'
 '28.93' '30.31' '29.76' '23.87' '28.49' '24.02' '23.94' '24.20' '28.52'
 '30.40' '24.45' '30.19' '30.30' '23.96' '30.28' '24.11' '24.09' '28.43'
 '28.98' '23.77' '28.44' '28.34' '23.82' '28.33' '28.38' '28.42' '24.18'
 '24.12' '28.67' '23.80' '28.29' '24.41' '28.75' '24.34' '23.97' '23.83'
 '28.28' '24.42' '28.39' '24.47' '28.73' '24.38' '28.18' '28.19' '28.20'
 '24.28' '28.57' '28.60' '24.22' '23.92' '23.99' '24.33' '24.25' '24.50'
 '24.44' '24.46' '24.35' '24.61' '24.15' '28.37' '24.04' '28.36' '28.35'
 '24.48' '30.53' '30.55' '30.43' '30.45' '24.07' '23.88' '23.90' '28.26'
 '23.76' '23.91' '28.32' '23.84' '30.57' '24.64' '30.44' '30.46' '30.50'
 '24.53' '24.62' '23.72' '24.57' '30.39' '30.38' '28.17' '28.16' '28.07'
 '28.31' '23.78' '30.59' '30.61' '23.74' '28.04' '24.52']
sealevel
 ['29.92' '29.91' '30.47' '30.48' '30.54' 'M' '30.09' '30.19' '30.18'
 '30.59' '30.52' '29.89' '30.50' '30.49' '29.79' '29.62' '30.63' '30.64'
 '30.66' '30.44' '30.14' '30.65' '29.58' '29.59' '30.20' '30.62' '29.87'
 '29.85' '30.34' '30.30' '30.12' '30.33' '30.23' '29.84' '30.36' '30.41'
 '30.26' '30.03' '30.01' '30.27' '30.28' '30.31' '30.06' '30.38' '30.37'
 '30.29' '30.02' '30.00' '30.11' '30.24' '30.13' '29.73' '30.21' '30.22'
 '30.04' '29.82' '29.83' '29.81' '29.99' '29.75' '30.16' '30.17' '29.93'
 '29.71' '29.76' '30.15' '30.07' '30.05' '30.08' '29.98' '29.97' '29.96'
 '29.86' '29.94' '29.95' '29.88' '30.10' '29.78' '29.64' '29.74' '29.69'
 '29.70' '29.41' '29.40' '29.38' '30.35' '29.80' '30.25' '30.43' '29.77'
 '30.45' '30.40' '29.90' '29.66' '29.44' '29.60' '29.63' '29.65' '30.51'
 '29.57' '29.56' '29.54' '30.39' '30.42' '30.32' '29.67' '30.46' '30.57'
 '30.67' '29.72' '29.68' '29.49' '29.51' '29.52' '29.61' '29.55' '29.53'
 '29.39' '29.43' '29.37' '29.36' '29.34' '29.50' '29.47' '29.48' '29.27'
 '29.28' '30.60' '30.70' '30.69' '30.55' '30.56' '29.42' '29.22' '29.25'
 '30.53' '30.61' '30.71' '30.73' '30.80' '30.58' '29.46' '29.45' '30.68'

In [45]:
def codesum_character(codesum):
    if codesum == ' ':
        return "moderate"
    else:
        return codesum

In [46]:
weather['codesum'] = weather['codesum'].apply(codesum_character)

In [47]:
def compare_codesum(codesum):
    if codesum =="moderate":
        return codesum
    else:
        return "abnormal"

In [48]:
weather['codsum_YN'] = weather['codesum'].apply(compare_codesum)

In [49]:
for i in weather.columns:
    weather[i] = weather[i].replace('-', np.nan)
    weather[i] = weather[i].replace(' ', np.nan)
    weather[i] = weather[i].replace('M', np.nan)
    weather[i] = weather[i].replace('T', np.nan)
    weather[i] = weather[i].replace('  T', np.nan)

In [50]:
for i in weather.columns:
    print(i, "\n", weather[i].unique())

date
 ['2012-01-01' '2012-01-02' '2012-01-03' ..., '2014-10-29' '2014-10-30'
 '2014-10-31']
tmax
 ['52' '48' '55' '63' '50' '66' '34' '73' '72' '38' '56' '59' '46' '45' '60'
 '44' '21' '65' '43' '53' '25' '32' '28' '62' '61' '47' '30' '26' '71' '58'
 '39' '54' '23' '27' '31' '68' '70' '67' '36' '69' '74' '75' '33' '51' '57'
 '41' '49' '76' '35' '77' '64' '40' '16' '37' '42' '14' '22' '13' '10' '20'
 '24' '80' '4' '11' '78' '17' '18' '79' '29' '81' '82' '83' '88' '87' '92'
 '89' '84' '85' '86' '90' '91' '94' '93' '96' '95' nan '97' '98' '101' '99'
 '100' '105' '103' '102' '106' '104' '109' '107' '108' '110' '111' '112'
 '114' '113' '19' '15' '12' '-1' '5' '8' '9' '1' '6' '2' '3' '7' '-2' '-11'
 '-4' '-6' '0']
tmin
 ['31' '33' '34' '47' '45' '19' '53' '48' '18' '26' '30' '38' '40' '25' '41'
 '28' '24' '37' '36' '11' '16' '29' '22' '35' '15' '9' '21' '27' '10' '5'
 '32' '20' '3' '8' '44' '46' '17' '55' '43' '57' '50' '49' '54' '42' '39'
 '52' '23' '56' '14' '59' '-1' '12' '6' '4' '2' '60' '51' '63' '-5' '7'
 '61' '13' '-11' '0' '-2' '58' '-7' '62' '66' '67' '64' '65' '69' '68' '70'
 '71' '73' '72' '75' '74' '76' '78' nan '77' '79' '80' '83' '81' '82' '86'
 '88' '85' '84' '1' '-3' '-6' '-9' '-4' '-10' '-8' '-13' '-12' '-17' '-19'
 '-21' '-14' '-16' '-15']
tavg
 ['42' '41' '45' '55' '49' nan '27' '63' '60' '28' '37' '40' '47' '50' '32'
 '35' '16' '52' '56' '33' '36' '34' '44' '20' '43' '22' '19' '38' '18' '13'
 '57' '51' '30' '46' '29' '26' '48' '31' '65' '54' '58' '24' '61' '62' '59'
 '53' '64' '25' '39' '67' '68' '14' '11' '10' '8' '5' '17' '66' '15' '-3'
 '23' '21' '7' '9' '70' '69' '72' '71' '12' '73' '75' '74' '76' '79' '78'
 '77' '80' '81' '82' '83' '84' '85' '87' '86' '90' '88' '89' '93' '92' '91'
 '95' '94' '97' '99' '96' '100' '98' '6' '3' '-5' '2' '4' '1' '-4' '0' '-2'
 '-1' '-10' '-16' '-8' '-6' '-7']
depart
 [nan '16' ' 9' ' 4' ' 0' ' 7' ' 5' '10' '12' '-1' '-2' '-4' '15' '-6' ' 2'
 '-5' '-18' '-3' '-11' '11' ' 6' '-15' '-8' ' 8' '14' '19' ' 1' '24' '23'
 '13' ' 3' '17' '22' '-9' '-10' '28' '25' '-7' '20' '-13' '21' '18' '26'
 '-17' '-16' '-14' '-20' '27' '-12' '31' '29' '32' '33' '-22' '-23' '-21'
 '30' '-19' '-24' '-27' '-25' '-26' '-28' '-32' '-31' '-35']
dewpoint
 ['36' '37' '24' '28' '31' '26' '34' '17' '55' '54' '12' '25' '35' '23' '11'
 '27' '29' '8' '33' '16' '10' '9' '21' '4' '19' '22' '2' '6' '18' '5' '-1'
 '0' '39' '41' '45' '15' '32' '13' '43' '46' '38' '52' '53' '44' '40' '47'
 '51' '48' '20' '49' '50' '14' '56' '30' '3' '7' nan '-5' '-3' '42' '-7'
 '59' '61' '57' '-15' '58' '60' '62' '64' '66' '-2' '65' '63' '67' '68'
 '69' '70' '71' '72' '74' '73' '75' '1' '-4' '-13' '-10' '-11' '-8' '-12'
 '-6' '-9' '76' '77' '-14' '-17' '-24' '-20' '-19' '-16']
wetbulb
 ['40' '39' '36' '43' '35' '46' '23' '58' '56' '57' '21' '38' '37' '30' '32'
 '28' '29' '15' '44' '17' '18' '16' '31' '33' '14' '11' '47' '45' '49' '26'
 '41' '25' '50' '52' '22' '42' nan '48' '53' '54' '51' '27' '55' '20' '34'
 '60' '59' '12' '10' '19' '13' '7' '5' '2' '62' '63' '64' '24' '61' '-4'
 '6' '4' '9' '65' '66' '67' '8' '68' '69' '70' '71' '72' '73' '74' '75'
 '76' '77' '78' '3' '-5' '-3' '0' '1' '79' '80' '-2' '-8' '-15' '-10' '-6'
 '-9' '-7' '-1']
heat
 ['23' '24' '20' '10' '16' nan '38' '2' '5' '37' '28' '25' '18' '15' '33'
 '30' '49' '13' '9' '32' '29' '31' '21' '45' '22' '43' '46' '27' '47' '52'
 '8' '14' '35' '19' '36' '39' '17' '34' '0' '11' '7' '41' '4' '3' '6' '12'
 '1' '40' '26' '51' '54' '55' '57' '60' '48' '50' '68' '42' '44' '58' '56'
 '53' '59' '62' '70' '63' '61' '64' '69' '65' '67' '66' '75' '81' '73' '71'
 '72']
cool
 [' 0' nan ' 2' ' 3' ' 1' ' 5' ' 4' ' 7' ' 6' ' 8' '10' ' 9' '11' '14' '13'
 '12' '15' '16' '17' '18' '19' '20' '22' '21' '25' '23' '24' '28' '27' '26'
 '30' '29' '32' '34' '31' '35' '33']
sunrise
 [  nan  436.  455.  448.  447.  443.  444.  459.  438.  450.  460.  451.
  445.  449.  442.  437.  435.  441.  454.  434.  440.  433.  458.  439.
  453.  432.  452.  457.  431.  430.  446.  456.  429.  428.  427.  426.
  425.  424.  423.  422.  421.  420.  419.  418.  417.  416.  414.  415.
  413.  412.  411.  409.  410.  408.  407.  405.  406.  404.  403.  401.
  400.  398.  397.  402.  396.  395.  394.  399.  393.  392.  391.  389.
  388.  387.  386.  385.  384.  379.  380.  383.  382.  381.  378.  377.
  376.  375.  374.  373.  372.  371.  370.  369.  368.  367.  366.  365.
  364.  363.  362.  360.  359.  358.  357.  355.  361.  390.  353.  352.
  351.  350.  348.  354.  346.  344.  343.  341.  347.  339.  345.  337.
  338.  336.  334.  332.  330.  331.  329.  327.  325.  326.  323.  324.
  322.  320.  318.  319.  316.  317.  315.  313.  314.  356.  311.  312.
  310.  308.  309.  306.  307.  305.  349.  303.  304.  301.  300.  298.
  299.  296.  302.  295.  342.  293.  340.  292.  290.  289.  291.  287.
  286.  288.  284.  333.  283.  285.  281.  280.  282.  279.  277.  328.
  276.  278.  335.  275.  273.  272.  271.  270.  268.  321.  267.  266.
  269.  265.  264.  263.  262.  261.  260.  259.  258.  257.  256.  255.
  254.  253.  252.  251.  250.  249.  248.  247.  246.  274.  294.  297.]
sunset
 [   nan   986.  1040.  1062.  1058.  1057.  1049.   981.  1052.   988.
   987.  1041.   982.  1053.   989.  1063.  1059.  1050.   983.  1054.
   990.  1042.  1064.  1060.  1051.   984.   991.  1043.  1065.   985.
  1055.  1044.  1061.  1056.   992.  1045.  1066.   993.  1046.  1067.
   995.   994.  1047.  1068.   996.  1069.   997.  1048.   998.  1070.
   999.  1071.  1000.  1072.  1001.  1073.  1002.  1074.  1004.  1003.
  1075.  1005.  1006.  1076.  1007.  1077.  1008.  1078.  1010.  1009.
  1079.  1011.  1080.  1012.  1081.  1014.  1015.  1016.  1082.  1017.
  1083.  1019.  1018.  1084.  1020.  1085.  1021.  1086.  1023.  1087.
  1024.  1088.  1025.  1027.  1089.  1022.  1028.  1090.  1029.  1091.
  1031.  1092.  1026.  1032.  1093.  1033.  1094.  1035.  1030.  1036.
  1034.  1095.  1037.  1096.  1039.  1097.  1038.  1098.  1099.  1100.
  1101.  1102.  1103.  1104.  1105.  1106.  1107.  1108.  1109.  1110.
  1111.  1112.  1113.  1114.  1115.  1116.  1117.  1118.  1119.  1120.
  1121.  1122.  1123.  1124.  1125.  1126.  1127.  1128.  1129.  1130.
  1131.  1132.  1133.  1134.  1135.  1136.  1137.  1138.  1139.  1140.
  1141.  1142.  1143.  1144.  1145.  1146.  1147.  1148.  1149.  1150.
  1151.  1152.  1153.  1154.  1155.  1156.  1157.  1158.  1159.  1160.
  1161.  1162.  1163.  1164.  1165.  1166.  1167.  1168.  1169.  1170.
  1171.  1172.  1173.  1174.  1175.  1176.  1177.  1178.  1179.  1180.
  1181.  1182.  1183.  1184.  1185.  1186.  1187.  1188.  1189.  1013.
   980.   979.   978.   977.   976.   975.   974.   973.   972.   971.]
codesum
 ['RA FZFG BR' 'RA' 'moderate' 'RA BR' 'UP' 'FG+ FG BR' 'RA FG+ FZFG BR'
 'RA MIFG BR' 'RA SN BR' 'SN UP' 'BR' 'SN' 'BR HZ' 'FG+ BR'
 'SN FG+ FZFG BR' 'RA HZ' 'RA BR HZ' 'FG BR' 'TSRA FG+ BR HZ'
 'RA BR HZ VCTS' 'TSRA RA DZ BR' 'TSRA RA DZ BR VCTS' 'TSRA RA BR'
 'RA BR VCTS' 'SN BR' 'TS TSRA RA DZ BR' 'SN FZFG BR'
 'RA SN FG+ FG FZFG BR UP' 'SN FZFG BR UP' 'DZ SN BR HZ'
 'RA FZRA FG+ FG BR UP' 'FZRA FG+ FZFG UP' 'FZRA SN BR UP' 'RA FG BR'
 'SN BR HZ' 'RA SN BR HZ' 'RA SN FG+ BR' 'DZ BR HZ' 'RA SN FG BR'
 'RA SN BR HZ BLSN' 'FZDZ BR' 'FG+ FG BR HZ' 'FG+ FG BCFG BR' 'FG+'
 'SN FZFG' 'BR HZ DU' 'DZ BR' 'BR HZ BLDU' 'FG+ BR HZ' 'RA FG+ FG BR'
 'BR HZ DU SQ' 'HZ DU' 'BR DU' 'DZ FZDZ BR' 'RA SN FG+ FG BR' 'BLDU'
 'FG+ FG' 'DU' 'TS RA BR HZ' 'BCFG BR' 'FG+ FG FZFG BR' 'RA DZ BR'
 'TS TSRA BR' 'TSRA RA DZ VCTS' 'RA FZRA SN BR UP' 'FZRA SN FG+ FZFG BR UP'
 'MIFG' 'SN BR UP HZ' 'RA FZRA BR' 'DZ' 'RA BCFG BR' 'HZ'
 'RA FG+ FG FZFG BR HZ' 'RA DZ FG+ BCFG BR' 'DZ FG BR HZ'
 'FG+ FZFG BR UP HZ' 'RA FG+ FZFG BR HZ' 'BCFG BR HZ'
 'RA DZ FG+ FG BR HZ VCTS' 'TSRA RA' 'TS RA BR VCTS' 'SN FZFG BR BLSN'
 'TS RA DZ BR' 'TSRA RA BR VCTS' 'TS RA BR' 'RA VCTS' 'RA DZ' 'RA DZ BR HZ'
 'FG+ FZFG BR' 'SN BR HZ BLSN' 'PL' 'DZ SN' 'DZ FZDZ SN BR'
 'FZRA SN FG+ FZFG BR' 'RA DZ FG BR' 'FZDZ SN BR' 'RA DZ SN FG BR'
 'DZ FG+ BCFG BR' 'DZ FG+ FG FZFG BR' 'RA UP' 'TSRA RA FG BR HZ'
 'DZ FG+ BR' 'RA FG+ BR' 'RA BR UP' 'TSRA' 'RA SN' 'FG+ BCFG BR HZ'
 'TS FG BR' 'FZFG BR' 'RA SN FG+ BR UP' 'SN BR UP' 'RA SN BR UP' 'SN FG BR'
 'RA DZ SN BR' 'FZRA SN FZFG BR' 'RA SN FG BR UP' 'SN FG+ FZFG BR UP'
 'RA FZRA FG+ FG FZFG BR' 'RA FZRA SN FZFG BR UP' 'FU' 'FZRA FZDZ SN BR'
 'RA DZ HZ' 'RA MIFG' 'RA DZ BR VCTS' 'RA DZ HZ VCTS' 'TSRA RA DZ FG BR'
 'TSRA RA DZ HZ' 'BR VCFG' 'TS' 'TS MIFG BR' 'MIFG BR' 'TSRA RA FG BR'
 'TSRA BR' 'BCFG' 'TSRA RA BR HZ' 'TSRA RA FG+ BR' 'DZ FG BR'
 'DZ FG+ FG BR' 'FG BCFG BR' 'TS FG+ FG BR' 'HZ FU' 'TS TSRA RA'
 'TS TSRA RA FG BR' 'TSRA RA BR SQ' 'HZ VCTS' 'TS RA HZ VCTS'
 'TS FG+ BR HZ' 'BR HZ VCTS' 'FG BR HZ' 'BR HZ FU' 'BR FU' 'RA BCFG BR HZ'
 'TS TSRA BR HZ' 'TS TSRA RA BR' 'TS VCTS' 'TSRA BR HZ' 'RA DZ VCTS'
 'TS RA' 'TSRA BR VCTS' 'VCTS' 'TS TSRA' 'TSRA RA VCTS' 'DZ HZ' 'TSRA VCTS'
 'TS BR' 'TS RA HZ FU' 'TS TSRA RA BR HZ FU' 'TSRA RA FG+ BR VCTS'
 'TSRA BR FU' 'TS TSRA RA DZ' 'MIFG FU' 'DZ BR HZ VCTS' 'TSRA HZ'
 'TSRA RA DZ BR HZ' 'TS BR FU' 'TS TSRA RA BCFG BR' 'RA BR FU'
 'TSRA RA FG BR VCTS' 'TS FU' 'RA FG BR HZ' 'TS TSRA VCTS'
 'TS TSRA RA BR VCTS' 'RA FG+ FG BR HZ VCTS' 'TS TSRA RA VCTS'
 'TS GR RA BR VCTS' 'BR VCTS' 'RA FG+ FG' 'RA DZ BR HZ VCTS'
 'RA FG+ BR HZ VCTS' 'TS RA VCTS' 'FG+ BCFG BR' 'TS RA FG' 'TS HZ VCTS'
 'RA FG+ BR VCTS' 'TS HZ' 'TS TSRA RA BR HZ' 'TS FG+ BR' 'RA BLDU SQ'
 'TS RA HZ' 'FG' 'TSRA RA BCFG BR HZ' 'TSRA FG+' 'RA HZ VCTS' 'TSRA RA SQ'
 'TSRA BR HZ VCTS' 'TS TSRA RA HZ' 'TS RA GS BR' 'RA FG BCFG BR'
 'RA DZ FG+ BR HZ' 'RA FG+' 'TSRA RA FG+ FG BR' 'DZ SN BR' 'DZ FG+ BR HZ'
 'TS RA DZ VCTS' 'TS RA BR HZ VCTS' 'RA SN FZFG BR' 'FZFG' 'RA SN BR UP HZ'
 'TS TSSN RA FG+ FG BR VCTS' 'TSSN RA SN FG+ FZFG BR' 'MIFG BR HZ'
 'FG+ FZFG' 'RA DZ BCFG BR' 'SN FG+ FG BR' 'FZRA SN BR'
 'RA FZRA FG+ FG FZFG BR UP' 'RA DZ FG+ BR' 'DZ SN FG+ FG BR UP'
 'RA FG+ FG BR UP' 'TSRA RA HZ VCTS' 'TS TSRA RA FG+ FG BR'
 'FZRA FG+ FZFG BR HZ' 'FG+ FZFG BCFG' 'RA FZRA SN BR'
 'RA FZRA SN FG+ FG FZFG BR' 'TS HZ BLDU' 'FZRA SN UP HZ' 'UP HZ'
 'TS TSRA RA SN FG BR' 'RA SN FG+ FZFG BR HZ' 'DZ SN FG BR' 'SN HZ'
 'RA SN FG FZFG BR' 'RA DZ SN FG+ BR' 'TSRA RA BCFG BR'
 'TSRA RA DZ SN FG HZ' 'RA FG+ FG MIFG BR' 'RA FG+ BR UP' 'DZ MIFG BR'
 'FG+ MIFG BR' 'FG MIFG BR' 'RA FZRA' 'FZRA' 'RA DZ SN' 'SG' 'BR UP HZ'
 'TS SN GS' 'FZRA SN FZFG BR UP' 'SN BLSN' 'FZRA PL BR HZ' 'BR UP'
 'FZRA FG+ FG FZFG BR UP' 'TSRA RA BR HZ VCTS' 'TSRA RA DZ'
 'RA FZRA FG+ BR' 'SN UP BLSN' 'SN HZ BLSN' 'RA FG+ FG BR HZ'
 'RA SN PL BR HZ' 'SN FG+ FZFG BR UP HZ' 'SN FG+ FG FZFG BR UP' 'SN UP HZ'
 'SN FG+ FZFG HZ' 'TS DZ BR' 'RA FZRA SN BR UP HZ' 'TSRA DZ BR'
 'RA FZRA SN FG+ FG FZFG BR UP' 'RA SN FG+ FG BR HZ' 'FG+ FZFG BR HZ'
 'SN BR UP BLSN' 'RA SN PL FG+ BR' 'RA SN FG+ FG BR UP'
 'TS TSRA RA DZ FZRA PL BR' 'TS TSRA RA FZRA BR' 'SN FZFG BR HZ'
 'TSRA RA FZRA BR UP VCTS' 'FZRA SN FG BR' 'SN FG+ FZFG BR BLSN'
 'TS TSRA RA SN PL BR' 'RA FZRA SN FG BR UP HZ VCTS' 'RA SN BR VCTS'
 'SN FG BR UP' 'SN FG+ FG FZFG BR' 'BCFG HZ' 'FZRA SN BR UP HZ'
 'RA SN FG FZFG BR UP' 'TSRA DZ HZ' 'RA SN UP' 'TS TSRA RA FG BR VCTS'
 'TS TSSN RA DZ SN BR' 'RA DZ SN BR HZ' 'TSSN RA DZ SN BR VCTS'
 'RA FZRA BR UP HZ' 'SN BR BLSN BLDU' 'RA FZRA BR VCTS' 'TSRA RA FZRA BR'
 'BR SQ' 'TS TSRA RA FG+ BR HZ VCTS' 'FZDZ SN FZFG BR' 'RA DZ FG BCFG BR'
 'TSRA RA DZ SN BR HZ VCTS' 'TSSN FG+ BR VCTS' 'TS TSRA FG+ BR HZ'
 'TS TSRA BR SQ' 'RA FG+ FG BR VCTS' 'TS RA FG+ BR HZ VCTS'
 'TS RA DZ BR HZ' 'TS TSRA GR RA BR' 'TSRA FG+ FG BR VCTS' 'TS TSRA DZ BR'
 'TS RA FG BR' 'TS TSRA RA FG+ FG VCTS' 'TS TSRA RA FG+'
 'TSRA TSSN BR HZ VCTS' 'DZ FG+ FG HZ' 'TS TSRA BR HZ VCTS' 'RA FG+ BR HZ'
 'TS BR HZ' 'TSRA BR SQ' 'RA FG BR VCTS' 'RA FG BR HZ VCTS' 'TS BR VCTS'
 'FG+ FG BR VCTS' 'TS RA FG+ BR' 'FG BR VCTS' 'TS SQ' 'VCFG' 'TS RA DZ'
 'TS RA DZ BR VCTS' 'RA FG+ FG BCFG BR' 'MIFG BCFG BR' 'TS RA GS'
 'RA FG MIFG BR' 'TSRA BCFG BR' 'RA DZ SN VCTS' 'RA FZFG BR HZ'
 'RA MIFG BCFG BR' 'FG+ FG MIFG BR' 'RA DZ FG+ FG BR HZ' 'RA FZRA BR HZ'
 'TS RA DZ HZ VCTS' 'RA FG BR HZ SQ' 'RA DZ FZRA FZDZ BR' 'FZRA UP'
 'FZRA BR UP' 'RA FZRA BR UP' 'RA SN FG+' 'SN PL' 'RA PL' 'DZ FZRA'
 'FZRA BR HZ' 'RA DZ SN HZ' 'RA FZRA SN FG+ BR UP' 'SN FG+ FG BR HZ'
 'RA DZ FG+ FG BR' 'RA DZ FG+ MIFG BR HZ' 'DZ FG+' 'FZRA SN UP'
 'RA FZRA FZDZ PL BR' 'FZRA BR' 'RA PL BR' 'FZDZ' 'FZDZ BR HZ'
 'PRFG BCFG BR HZ' 'RA FZRA SN BR HZ' 'SN BR BLSN' 'RA DZ FZRA BR HZ'
 'FZRA BR UP HZ' 'DZ FZRA FZDZ SN BR' 'DZ SN FG+ FZFG BR'
 'RA FZRA FG+ FZFG BR UP' 'RA FZRA FG+ FG BR' 'SN FG+ FZFG BR HZ' 'BLSN'
 'FZDZ SN BLSN' 'RA FG+ BCFG BR' 'SN FG+ BR HZ' 'TSRA FG+ FG BR'
 'SN FG FZFG BR' 'SN FZFG UP' 'RA FZRA SN UP' 'RA FZRA PL BR' 'RA DZ UP'
 'FZRA PL' 'RA FZRA UP' 'SN FZFG BLSN' 'FG+ FG FZFG BR HZ' 'FZFG BR HZ'
 'SN FG+ FZFG' 'RA DZ BR UP HZ' 'RA BR UP HZ' 'FZRA SN FZFG BR UP HZ'
 'RA FG+ BCFG BR HZ' 'RA DZ FZRA FZDZ SN FG+ FG BR HZ' 'SN FG+ FZFG UP'
 'DZ FZDZ BR HZ' 'RA DZ BR UP' 'GS BR HZ' 'FZDZ FG BR HZ' 'RA DZ FZDZ BR'
 'RA SN FG+ FZFG BR' 'RA SN FG+ FG FZFG BR' 'UP BLSN'
 'FZRA SN FG+ FZFG BR HZ' 'HZ BLDU' 'TSRA RA SN FG+ BR HZ'
 'RA FG+ FZFG BR UP' 'TSRA RA FG+ FG BR UP' 'FZRA FZDZ BR'
 'RA FZRA FG+ FG BR HZ' 'RA DZ FZDZ FG+ BR' 'TS FZDZ SN BR BLSN'
 'FZRA SN VCTS' 'RA DZ SN BR UP' 'TS FZDZ SN BLSN'
 'FZRA SN FZFG BR UP BLSN' 'RA DZ FZDZ SN PL BR' 'TS TSRA FZRA'
 'TS RA FZRA BR VCTS' 'TSSN UP VCTS' 'TSSN SN BR UP' 'RA PL HZ'
 'RA FZRA FG BR HZ' 'FZRA FG FZFG BR' 'RA DZ SN FG FZFG BR'
 'TS TSRA GR RA BR HZ SQ' 'TSSN BR' 'TSRA RA FG' 'RA DU' 'TSRA RA SN BR'
 'TS TSRA FG+ BR' 'TSRA FG BR' 'DZ BR VCTS' 'TS TSRA HZ' 'TSRA FG+ BR'
 'TS TSRA BR VCTS' 'TS RA FG+ FG BR VCTS' 'TS TSRA RA DZ FG+ FG BR VCTS'
 'TSRA DZ BR VCTS']
snowfall
 [nan '0.0' '0.5' '0.2' '3.6' '3.7' '6.1' '0.6' '0.3' '2.0' '1.2' '1.4'
 '2.3' '1.3' '1.0' '4.3' '0.1' '1.7' '0.7' '1.9' '0.9' '0.4' '1.6' '4.7'
 '4.0' '2.1' '7.1' '4.2' '1.8' '5.2' '0.8' '1.5' '2.8' '3.0' '5.0' '9.3'
 '2.6' '3.1' '4.4' '3.4' '1.1' '5.5' '15.2' '7.8' '13.5' '16.2' '3.5' '2.2'
 '3.2' '13.1' '4.6' '2.4' '5.4' '7.2' '14.9' '7.7' '11.0' '2.9' '5.1' '3.3'
 '3.9' '7.0' '6.6' '8.0' '4.9' '6.2' '6.4' '4.1' '5.8' '2.7' '12.2' '10.5'
 '6.7' '3.8' '5.7' '2.5']
preciptotal
 ['0.05' '0.07' '0.00' nan '0.09' '0.12' '0.01' '0.02' '0.16' '0.03' '0.13'
 '0.87' '0.62' '1.32' '1.58' '0.49' '0.30' '0.04' '0.69' '1.06' '0.34'
 '0.98' '0.35' '0.11' '0.06' '0.15' '0.08' '0.22' '0.14' '0.20' '0.25'
 '0.31' '0.17' '0.24' '0.40' '0.82' '1.52' '1.44' '1.75' '0.52' '3.14'
 '5.67' '3.00' '0.71' '3.06' '2.61' '0.21' '0.23' '0.19' '1.14' '1.20'
 '1.15' '0.38' '0.48' '0.84' '0.91' '1.33' '0.67' '1.70' '0.10' '0.27'
 '0.18' '0.53' '0.59' '0.70' '1.72' '1.10' '1.56' '1.82' '0.77' '1.04'
 '0.80' '0.50' '0.56' '0.51' '0.58' '0.47' '0.54' '0.61' '0.81' '0.64'
 '0.65' '0.45' '0.36' '0.33' '1.27' '1.08' '0.96' '0.86' '1.01' '0.28'
 '0.39' '1.39' '0.42' '0.90' '2.81' '2.34' '0.89' '3.02' '3.05' '2.40'
 '2.85' '1.43' '2.77' '2.69' '2.16' '1.07' '2.09' '2.05' '0.46' '0.32'
 '1.18' '0.75' '0.60' '1.30' '0.73' '0.88' '2.75' '0.93' '0.26' '0.78'
 '1.19' '0.92' '1.00' '0.68' '0.63' '1.05' '0.85' '1.67' '1.36' '1.23'
 '1.90' '0.83' '1.28' '0.76' '0.79' '2.45' '0.43' '0.44' '2.70' '1.17'
 '2.84' '0.37' '1.64' '0.95' '0.72' '1.12' '2.15' '1.78' '2.68' '1.09'
 '2.83' '1.40' '1.81' '1.96' '0.41' '3.32' '0.29' '2.10' '1.71' '0.99'
 '2.21' '1.66' '1.45' '5.12' '3.47' '2.91' '0.66' '1.99' '1.47' '1.22'
 '0.57' '4.65' '7.36' '6.93' '4.84' '5.20' '5.36' '1.11' '1.38' '1.24'
 '1.53' '2.23' '1.03' '0.55' '1.55' '2.50' '2.27' '2.04' '2.35' '1.21'
 '1.16' '3.91' '1.37' '1.95' '1.35' '1.41' '1.29' '1.42' '0.94' '3.52'
 '1.91' '2.38' '3.34' '2.37' '2.56' '1.49' '1.98' '2.65' '1.89' '1.85'
 '0.74' '0.97' '1.80' '3.20' '1.57' '1.79' '3.19' '2.31' '2.03' '2.57'
 '1.34' '1.13' '1.50' '2.42' '3.03' '2.06' '1.88' '2.82' '2.92' '3.30'
 '3.13' '5.59' '5.65' '2.00' '2.18' '1.94' '2.28' '1.69' '2.60' '2.12'
 '1.92' '1.73' '1.76' '1.63' '2.48' '3.53' '2.13' '1.60' '1.02' '1.61'
 '1.65' '1.68' '1.31' '2.20' '2.76' '1.46' '1.54' '1.25' '2.02' '4.22'
 '3.16' '3.24' '2.49' '2.11' '1.83' '1.93' '1.87' '2.01' '1.62' '3.27'
 '3.07' '2.14' '2.07' '2.59' '3.17' '2.32' '1.26' '2.88' '1.77' '2.41'
 '3.66' '3.45' '5.04']
stnpressure
 ['29.78' '28.82' '29.77' '29.79' '29.95' '29.15' '30.05' '29.34' '30.16'
 '30.15' '24.60' '29.13' '29.53' '29.80' '29.83' '29.98' '29.06' '29.44'
 '28.51' '29.89' '29.93' '30.09' '29.23' '30.25' '29.67' '30.11' '30.10'
 '24.55' '29.21' '29.20' '29.48' '29.96' '29.47' '29.90' '28.69' '29.55'
 '29.70' '29.88' '28.84' '30.12' '29.26' '30.27' '30.26' '24.40' '29.61'
 '29.84' '29.43' '29.63' '29.86' '28.87' '29.72' '28.90' '30.35' '30.34'
 '24.49' '28.89' '29.59' '29.75' '29.54' '28.70' '29.35' '29.51' '29.68'
 '28.71' '29.87' '28.95' '30.20' nan '30.18' '24.26' '29.42' '29.66'
 '29.02' '29.46' '29.16' '29.65' '29.00' '30.14' '24.21' '28.50' '29.39'
 '29.19' '29.57' '28.63' '29.36' '24.19' '28.66' '29.60' '29.41' '29.32'
 '29.27' '29.45' '29.31' '28.78' '29.64' '30.17' '24.32' '28.76' '29.50'
 '29.56' '30.06' '29.05' '29.33' '28.79' '29.17' '30.13' '24.37' '28.77'
 '29.81' '29.52' '29.69' '28.74' '29.24' '30.03' '30.02' '24.13' '29.22'
 '29.14' '29.91' '28.92' '29.08' '29.10' '29.28' '28.47' '28.99' '24.24'
 '28.45' '28.85' '29.62' '28.62' '28.72' '28.30' '29.94' '30.04' '24.23'
 '29.11' '29.58' '28.64' '28.83' '29.99' '28.81' '29.73' '29.38' '29.29'
 '28.61' '30.36' '24.01' '29.85' '30.29' '29.03' '29.49' '28.41' '30.42'
 '30.41' '23.98' '30.32' '29.01' '30.24' '30.22' '29.40' '24.05' '28.48'
 '30.08' '23.95' '29.12' '29.30' '28.46' '24.06' '29.04' '28.56' '23.75'
 '28.27' '30.07' '23.93' '28.80' '29.97' '29.25' '29.18' '28.59' '30.00'
 '30.01' '24.16' '28.58' '29.07' '24.29' '24.36' '28.88' '24.31' '30.37'
 '24.10' '30.33' '29.71' '30.21' '24.27' '28.65' '30.23' '24.39' '28.55'
 '24.51' '28.97' '28.96' '29.82' '28.86' '24.30' '24.43' '29.92' '28.53'
 '28.94' '28.91' '28.54' '24.17' '29.74' '29.37' '28.68' '24.14' '23.89'
 '24.00' '24.03' '29.09' '28.22' '23.85' '28.40' '28.25' '24.08' '28.23'
 '28.93' '30.31' '29.76' '23.87' '28.49' '24.02' '23.94' '24.20' '28.52'
 '30.40' '24.45' '30.19' '30.30' '23.96' '30.28' '24.11' '24.09' '28.43'
 '28.98' '23.77' '28.44' '28.34' '23.82' '28.33' '28.38' '28.42' '24.18'
 '24.12' '28.67' '23.80' '28.29' '24.41' '28.75' '24.34' '23.97' '23.83'
 '28.28' '24.42' '28.39' '24.47' '28.73' '24.38' '28.18' '28.19' '28.20'
 '24.28' '28.57' '28.60' '24.22' '23.92' '23.99' '24.33' '24.25' '24.50'
 '24.44' '24.46' '24.35' '24.61' '24.15' '28.37' '24.04' '28.36' '28.35'
 '24.48' '30.53' '30.55' '30.43' '30.45' '24.07' '23.88' '23.90' '28.26'
 '23.76' '23.91' '28.32' '23.84' '30.57' '24.64' '30.44' '30.46' '30.50'
 '24.53' '24.62' '23.72' '24.57' '30.39' '30.38' '28.17' '28.16' '28.07'
 '28.31' '23.78' '30.59' '30.61' '23.74' '28.04' '24.52']
sealevel
 ['29.92' '29.91' '30.47' '30.48' '30.54' nan '30.09' '30.19' '30.18'
 '30.59' '30.52' '29.89' '30.50' '30.49' '29.79' '29.62' '30.63' '30.64'
 '30.66' '30.44' '30.14' '30.65' '29.58' '29.59' '30.20' '30.62' '29.87'
 '29.85' '30.34' '30.30' '30.12' '30.33' '30.23' '29.84' '30.36' '30.41'
 '30.26' '30.03' '30.01' '30.27' '30.28' '30.31' '30.06' '30.38' '30.37'
 '30.29' '30.02' '30.00' '30.11' '30.24' '30.13' '29.73' '30.21' '30.22'
 '30.04' '29.82' '29.83' '29.81' '29.99' '29.75' '30.16' '30.17' '29.93'
 '29.71' '29.76' '30.15' '30.07' '30.05' '30.08' '29.98' '29.97' '29.96'
 '29.86' '29.94' '29.95' '29.88' '30.10' '29.78' '29.64' '29.74' '29.69'
 '29.70' '29.41' '29.40' '29.38' '30.35' '29.80' '30.25' '30.43' '29.77'
 '30.45' '30.40' '29.90' '29.66' '29.44' '29.60' '29.63' '29.65' '30.51'
 '29.57' '29.56' '29.54' '30.39' '30.42' '30.32' '29.67' '30.46' '30.57'
 '30.67' '29.72' '29.68' '29.49' '29.51' '29.52' '29.61' '29.55' '29.53'
 '29.39' '29.43' '29.37' '29.36' '29.34' '29.50' '29.47' '29.48' '29.27'
 '29.28' '30.60' '30.70' '30.69' '30.55' '30.56' '29.42' '29.22' '29.25'
 '30.53' '30.61' '30.71' '30.73' '30.80' '30.58' '29.46' '29.45' '30.68'

# Data conversion to float

In [51]:
weather.columns

Index(['date', 'tmax', 'tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat',
       'cool', 'sunrise', 'sunset', 'codesum', 'snowfall', 'preciptotal',
       'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed',
       'codsum_YN'],
      dtype='object')

In [52]:
for col in weather[['tmax','tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat', 'cool', 
                 'sunrise', 'sunset', 'snowfall', 'preciptotal', 'stnpressure','sealevel',
                 'resultspeed', 'resultdir', 'avgspeed']]:
    weather[col] = weather[col].astype(np.float64)
    
weather = pd.DataFrame(weather, columns=['date','tmax', 'tmin', 'tavg', 'depart', 'dewpoint', 'wetbulb', 'heat',
       'cool', 'sunrise', 'sunset', 'codesum','codsum_YN', 'snowfall', 'preciptotal',
       'stnpressure', 'sealevel', 'resultspeed', 'resultdir', 'avgspeed'])

### total np.nan count

In [53]:
print(len(weather))

for i in weather.columns:
    sum = weather[i].isnull().sum()
    print(i, "- null count :", sum, "(",(sum / 20517 * 100).round(2),"%",")")

19665
date - null count : 0 ( 0.0 % )
tmax - null count : 84 ( 0.41 % )
tmin - null count : 86 ( 0.42 % )
tavg - null count : 647 ( 3.15 % )
depart - null count : 10689 ( 52.1 % )
dewpoint - null count : 220 ( 1.07 % )
wetbulb - null count : 400 ( 1.95 % )
heat - null count : 647 ( 3.15 % )
cool - null count : 647 ( 3.15 % )
sunrise - null count : 9625 ( 46.91 % )
sunset - null count : 9625 ( 46.91 % )
codesum - null count : 0 ( 0.0 % )
codsum_YN - null count : 0 ( 0.0 % )
snowfall - null count : 6713 ( 32.72 % )
preciptotal - null count : 2448 ( 11.93 % )
stnpressure - null count : 77 ( 0.38 % )
sealevel - null count : 1277 ( 6.22 % )
resultspeed - null count : 143 ( 0.7 % )
resultdir - null count : 143 ( 0.7 % )
avgspeed - null count : 53 ( 0.26 % )

In [54]:
def vis_null_count():
    station_nbr = int(input())
    print("Counting missing values for station_nbr_", station_nbr)
    i = station_nbr
    dic = {}
    for j in weather.columns:
        sum = weather.loc[i][j].isnull().sum()
        print(j, "- null count :", sum, "(",(sum / 20517 * 100).round(2),"%",")")
        dic[j] = sum
    columns = list(dic.keys())
    counts = list(dic.values())
    fig_size = plt.rcParams["figure.figsize"]
    fig_size[0] = 18
    fig_size[1] = 3
    # fig = plt.figure(size=(4, 2))
    plt.title('station number np.nan count')
    plt.bar(columns, counts )

* * * *

## Missing Data에 대한 생각



1번 유형 - 바로 이전 날의 데이터를 참조
- tmax
- tmin
- tavg
- dewpoint
- wetbulb
- heat
- cool
- snowfall
- preciptotal
- stnpressure
- sealevel
- resultspeed
- reusltdir
- avgspeed

2번 유형 - null값의 비율이 지나치게 높다
- depart
- sunrise
- sunset

## Missing Data를 채워넣는 방법 고민 (수정)



- `tmax` = 전 날 참조 
- `tmin` = 전 날 참조

- `depart` = 첫 row는 0 으로 채워넣은 후, 전 날 참조
        - 지난 30년의 평균값 - `tmax` 값이므로, '현재로서는 평균값과 차이가 없다' 라는 주장이 제일 오차를 줄일 수 있을 것 같다.

- `wetbulb 습도` = 전 날 참조
- `dewpoint 이슬점` = 전 날 참조


- `sunrise-sunset` = 전 날 참조

- `preciptotal` = 전 날을 참조

- `station pressure 기압` = 전 날 참조
- `sealevel 해면기압` = 전 날 참조 
- `resultdir` = 전 날 참조
- `avgspeed` = 전 날 참조



- `tavg` = (`tmax` + `tmin` / 2) 반올림
- `heat` = 65 - `tavg`   (난방 지수)
- `cool` = `tavg` + 65   (냉방 지수)
        - 기준 온도 화씨 65도 (18도) (참조 : https://www.wunderground.com/about/faq/degreedays.asp)
        
- `snowfall` = preciptotal의 값을 참조

In [55]:
weather = weather.reset_index(drop=False)

In [56]:
weather = weather.sort_values(by=['station_nbr', 'date']).reset_index(drop=True)

In [57]:
weather.columns

Index(['station_nbr', 'date', 'tmax', 'tmin', 'tavg', 'depart', 'dewpoint',
       'wetbulb', 'heat', 'cool', 'sunrise', 'sunset', 'codesum', 'codsum_YN',
       'snowfall', 'preciptotal', 'stnpressure', 'sealevel', 'resultspeed',
       'resultdir', 'avgspeed'],
      dtype='object')

In [58]:
weather.describe()

,station_nbr,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,sunrise,sunset,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed
count,19665.000000,19581.000000,19579.000000,19018.000000,8976.000000,19445.000000,19265.000000,19018.000000,19018.000000,10040.000000,10040.000000,12952.000000,17217.000000,19588.000000,18388.000000,19522.000000,19522.000000,19612.000000
mean,10.789474,71.621010,50.651719,61.238301,1.366533,47.443610,53.888243,9.712798,5.951099,364.971315,1107.970916,0.045012,0.114673,29.162770,30.008704,6.406490,18.676365,7.910820
std,5.772850,19.860523,19.151364,19.207381,7.651024,19.362215,17.017772,13.852154,7.837831,52.858203,53.554139,0.506155,0.364658,1.245414,0.190385,4.163851,9.671965,3.934184
min,1.000000,-11.000000,-21.000000,-16.000000,-35.000000,-24.000000,-15.000000,0.000000,0.000000,246.000000,971.000000,0.000000,0.000000,23.720000,29.160000,0.000000,1.000000,0.000000
25%,6.000000,59.000000,37.000000,48.000000,-3.000000,33.000000,42.000000,0.000000,0.000000,329.000000,1068.000000,0.000000,0.000000,29.110000,29.890000,3.200000,13.000000,5.100000
50%,11.000000,76.000000,53.000000,65.000000,2.000000,51.000000,57.000000,0.000000,0.000000,365.000000,1115.000000,0.000000,0.000000,29.410000,30.000000,5.600000,18.000000,7.300000
75%,16.000000,87.000000,67.000000,77.000000,6.000000,64.000000,68.000000,17.000000,12.000000,408.000000,1155.000000,0.000000,0.020000,29.780000,30.120000,8.800000,26.000000,10.100000
max,20.000000,114.000000,88.000000,100.000000,33.000000,77.000000,80.000000,81.000000,35.000000,460.000000,1189.000000,16.200000,7.360000,30.610000,30.800000,28.400000,36.000000,28.700000

### `depart` 값 조정

In [59]:
weather.loc[0, 'depart'] = 0

In [60]:
weather.loc[0, 'depart']

0.0

### `sunrise` `sunset` 값 조정

In [61]:
weather['month'] = ""

for i in range(len(weather)):
    weather.loc[i, 'month'] = weather.loc[i, 'date'][5:7]

weather['month'] = weather['month'].astype(np.float64)

In [62]:
weather[weather['month'].isin([1])].describe()

,station_nbr,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,sunrise,sunset,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed,month
count,1767.000000,1765.000000,1766.000000,1695.000000,558.000000,1758.000000,1744.000000,1695.000000,1695.00000,620.000000,620.000000,1125.000000,1510.000000,1763.000000,1657.000000,1765.000000,1765.000000,1765.000000,1767.0
mean,10.789474,51.125779,29.267837,39.912684,4.770609,26.920364,35.154817,25.280236,0.19292,443.990323,1047.077419,0.102933,0.074318,29.231843,30.100392,6.981530,22.170538,8.510878,1.0
std,5.774337,17.979172,15.910556,16.368850,9.149530,17.704860,15.179859,16.038028,0.98030,8.329051,31.754620,0.575509,0.298209,1.275975,0.229834,4.187696,9.892095,4.110549,0.0
min,1.000000,-11.000000,-21.000000,-16.000000,-18.000000,-24.000000,-15.000000,0.000000,0.00000,422.000000,981.000000,0.000000,0.000000,23.750000,29.220000,0.000000,1.000000,0.700000,1.0
25%,6.000000,38.000000,19.000000,30.000000,-2.000000,15.000000,26.000000,13.000000,0.00000,438.000000,1014.000000,0.000000,0.000000,29.110000,29.960000,3.700000,17.000000,5.400000,1.0
50%,11.000000,53.000000,30.000000,41.000000,5.000000,26.000000,35.000000,24.000000,0.00000,444.000000,1061.000000,0.000000,0.000000,29.500000,30.120000,6.300000,23.000000,8.000000,1.0
75%,16.000000,65.000000,40.000000,52.000000,11.000000,40.000000,46.000000,35.000000,0.00000,449.000000,1071.000000,0.000000,0.010000,29.875000,30.250000,9.700000,30.000000,11.200000,1.0
max,20.000000,85.000000,72.000000,74.000000,30.000000,66.000000,69.000000,81.000000,9.00000,460.000000,1086.000000,6.400000,5.670000,30.420000,30.740000,23.000000,36.000000,23.200000,1.0

In [63]:
# 1월의 mean값을 통해 missing data를 채워넣는다
weather.loc[0, 'sunrise'] = weather[weather['month'].isin([1])].describe().loc['mean', 'sunrise'].round()
weather.loc[0, 'sunset'] = weather[weather['month'].isin([1])].describe().loc['mean', 'sunset'].round()

In [64]:
weather.loc[0, 'sunrise'], weather.loc[0, 'sunset']

(444.0, 1047.0)

### 전 날 참조 함수

In [65]:
def fill_prev():
    for columns in weather[['tmax', 'tmin', 'depart', 'dewpoint',
       'wetbulb', 'sunrise', 'sunset',
       'preciptotal', 'stnpressure', 'sealevel', 'resultspeed',
       'resultdir', 'avgspeed']]:
        for i in range(1, len(weather)):
            if np.isnan(weather.loc[i, columns]) == False:
                weather.loc[i, columns]
            elif np.isnan(weather.loc[i, columns]) == True:
                weather.loc[i, columns] = weather.loc[i-1, columns]

In [66]:
fill_prev()

In [67]:
weather.describe()

,station_nbr,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,sunrise,sunset,snowfall,preciptotal,stnpressure,sealevel,resultspeed,resultdir,avgspeed,month
count,19665.000000,19665.000000,19665.000000,19018.000000,19665.000000,19665.000000,19665.000000,19018.000000,19018.000000,19665.000000,19665.000000,12952.000000,19665.000000,19665.000000,19665.000000,19665.000000,19665.000000,19665.000000,19665.000000
mean,10.789474,71.583321,50.593033,61.238301,-0.184694,47.451411,53.782202,9.712798,5.951099,382.734350,1075.005492,0.045012,0.116440,29.163127,30.027730,6.398647,18.670074,7.911091,6.228019
std,5.772850,19.863483,19.175520,19.207381,5.603596,19.398190,17.145156,13.852154,7.837831,44.192959,54.660093,0.506155,0.364965,1.244834,0.201926,4.159333,9.666388,3.935745,3.321249
min,1.000000,-11.000000,-21.000000,-16.000000,-35.000000,-24.000000,-15.000000,0.000000,0.000000,246.000000,971.000000,0.000000,0.000000,23.720000,29.160000,0.000000,1.000000,0.000000,1.000000
25%,6.000000,59.000000,36.000000,48.000000,-2.000000,33.000000,41.000000,0.000000,0.000000,363.000000,1047.000000,0.000000,0.000000,29.110000,29.900000,3.200000,13.000000,5.100000,3.000000
50%,11.000000,76.000000,53.000000,65.000000,0.000000,51.000000,57.000000,0.000000,0.000000,393.000000,1065.000000,0.000000,0.000000,29.410000,30.010000,5.600000,18.000000,7.300000,6.000000
75%,16.000000,87.000000,67.000000,77.000000,1.000000,64.000000,68.000000,17.000000,12.000000,404.000000,1117.000000,0.000000,0.030000,29.780000,30.150000,8.800000,26.000000,10.100000,9.000000
max,20.000000,114.000000,88.000000,100.000000,33.000000,77.000000,80.000000,81.000000,35.000000,460.000000,1189.000000,16.200000,7.360000,30.610000,30.800000,28.400000,36.000000,28.700000,12.000000

### `tavg` 처리

In [68]:
for i in range(len(weather)):
    if np.isnan(weather.loc[i, 'tavg']) == True :
        weather.loc[i, 'tavg'] = ((weather.loc[i, 'tmax'] + weather.loc[i, 'tmin']) / 2).round()

In [69]:
print(len(weather[np.isnan(weather['tavg']) == True]))
weather[np.isnan(weather['tavg']) == True]

0

Empty DataFrame
Columns: [station_nbr, date, tmax, tmin, tavg, depart, dewpoint, wetbulb, heat, cool, sunrise, sunset, codesum, codsum_YN, snowfall, preciptotal, stnpressure, sealevel, resultspeed, resultdir, avgspeed, month]
Index: []

[0 rows x 22 columns]

### `heat`, `cool` 처리

In [70]:
weather[weather['station_nbr'].isin([2])][['heat', 'cool']].describe()

              heat         cool
count  1023.000000  1023.000000
mean     16.619746     1.632454
std      16.038392     3.524280
min       0.000000     0.000000
25%       0.000000     0.000000
50%      12.000000     0.000000
75%      30.000000     0.000000
max      62.000000    19.000000

In [71]:
for i in range(len(weather)):
    if np.isnan(weather.loc[i, 'heat']) == True :
        weather.loc[i, 'heat'] = (65 - weather.loc[i, 'tavg']).round()

In [72]:
print(len(weather[np.isnan(weather['heat']) == True]))
weather[np.isnan(weather['heat']) == True]

0

Empty DataFrame
Columns: [station_nbr, date, tmax, tmin, tavg, depart, dewpoint, wetbulb, heat, cool, sunrise, sunset, codesum, codsum_YN, snowfall, preciptotal, stnpressure, sealevel, resultspeed, resultdir, avgspeed, month]
Index: []

[0 rows x 22 columns]

In [73]:
for i in range(len(weather)):
    if np.isnan(weather.loc[i, 'cool']) == True :
        weather.loc[i, 'cool'] = (weather.loc[i, 'tavg'] - 65).round()

In [74]:
print(len(weather[np.isnan(weather['cool']) == True]))
weather[np.isnan(weather['cool']) == True]

0

Empty DataFrame
Columns: [station_nbr, date, tmax, tmin, tavg, depart, dewpoint, wetbulb, heat, cool, sunrise, sunset, codesum, codsum_YN, snowfall, preciptotal, stnpressure, sealevel, resultspeed, resultdir, avgspeed, month]
Index: []

[0 rows x 22 columns]

### `snowfall`처리

In [75]:
def fill_snowfall():
    for i in range(len(weather)):
        if np.isnan(weather.loc[i, 'snowfall']) == True:
            weather.loc[i, 'snowfall'] = weather.loc[i, 'preciptotal']
        elif np.isnan(i) == False:
            pass

In [76]:
fill_snowfall()

In [80]:
del weather['month']

In [81]:
weather.isnull().sum()

station_nbr    0
date           0
tmax           0
tmin           0
tavg           0
depart         0
dewpoint       0
wetbulb        0
heat           0
cool           0
sunrise        0
sunset         0
codesum        0
codsum_YN      0
snowfall       0
preciptotal    0
stnpressure    0
sealevel       0
resultspeed    0
resultdir      0
avgspeed       0
dtype: int64

In [82]:
weather.to_csv("weather_refer_prev_data.csv")